facebookexperimental/object-introspection

website/docusaurus.config.js
For real this time...
Double check the link is correct :(
=> Actually fix code link to website

.gitmodules
Update drgn to fix invalid pop from iterator code
CI, and manual review. Hoping that this should be fairly uncontroversial (if we were relying on this, I will really despise it :P)
=> Update drgn to fix invalid pop from iterator code

.circleci/config.yml, .gitmodules, src/TreeBuilder.cpp, test/integration/CMakeLists.txt, test/integration/sorted_vector_set.toml, types/sorted_vec_set_type.toml
Fixes `sorted_vector_set` and adds tests.
- CI
- D43547429
=> sorted_vec_set: finish changing to a container adapter

website/yarn.lock
Perform a `yarn upgrade`. This should resolve the dependabot warnings we've been getting recently.
- `yarn start` - looks good.
=> website: yarn upgrade

test/integration/cycles.toml
Integration tests: Set expected results for cycles.toml
Format the raw_ptr test case with jq to remove tabs and deleted extra data from the JSON.
=> Integration tests: Set expected results for cycles.toml

README.md
Would be good to display the logo on the landing page.
Describe what your change accomplishes
Check that OI is working correctly, you can add some unit or integration test,
paste the output of some manual test, and / or paste the output of running
the test locally with `make test-static`
=> Display the logo

oi/SymbolService.cpp
This change switches OID from the behemoth custom `drgn_program_find_type_by_symbol_name` to the nearly upstreamable `drgn_program_find_function_by_address`.
- `make test`
- CI
=> drgn: switch to Program.function_by_address()

oi/SymbolService.cpp
Rebases our drgn fork on main. There was a big refactor from `drgn_module` to `drgn_elf_file` so lots of changes there. Other than that it was pretty quiet, and two of our commits are now upstream bringing us down to 25.
- `make test`
- CI
=> drgn: rebase on main

oi/EnumBitset.h, oi/Features.h
To allow it to be reused with other enums
=> Turn FeatureSet into a generic EnumBitset

oi/type_graph/Flattener.cpp, test/test_flattener.cpp
Turn the parent container into a member so that we process it along with any extra members that this derived class has.
Depends on #176 for testing improvements.
=> Flattener: Handle classes which inherit from containers

oi/OITraceCode.cpp
Removes some bits from tracing code that are no longer needed. This addresses issue #132 .
@arsarwade says that `AllocAligned` and `AlignedDeleter` are both vestiges of how we used to handle template parameters with custom allocators so can go. @ajor, I added you as a reviewer to check you're happy with that and have no need for them.
I have successfully codegen'd an `Adunit` and and an `AdIndexerUnit`. No new test failures are seen.
=> remove unused old code from trace code

oi/CodeGen.cpp, oi/CodeGen.h, oi/ContainerTypeEnum.h, oi/TreeBuilder.cpp, test/integration/thrift_namespaces.toml, types/thrift_isset_type.toml
11 more tests pass, no new failures.
Before:
```
$ OID_TEST_ARGS='-ftype-graph' make test
...
94% tests passed, 36 tests failed out of 590
...
The following tests FAILED:
123 - integration_py (Timeout)
125 - OidIntegration.thrift_isset_missing_present (Failed)
126 - OidIntegration.thrift_isset_missing_missing (Failed)
127 - OidIntegration.thrift_isset_missing_mixed (Failed)
128 - OidIntegration.thrift_isset_unpacked (Failed)
129 - OidIntegration.thrift_isset_packed (Failed)
130 - OidIntegration.thrift_isset_packed_non_atomic (Failed)
131 - OidIntegration.thrift_isset_out_of_order (Failed)
132 - OidIntegration.thrift_isset_required (Failed)
133 - OidIntegration.thrift_isset_box (Failed)
163 - OidIntegration.std_string_empty (Failed)
164 - OidIntegration.std_string_sso (Failed)
165 - …
```
=> CodeGen: Add support for capturing Thrift isset data

include/oi/types/st.h, oi/CodeGen.cpp, oi/FuncGen.cpp
Comment the logic for `-ftyped-data-segment`. Trivial functional changes.
- `make test`
- CI
=> comment existing typed data segment work

oi/type_graph/TypeIdentifier.cpp, oi/type_graph/TypeIdentifier.h, test/test_add_padding.cpp, test/test_type_identifier.cpp
=> TypeGraph: Add boilerplate code and unit tests in preparation for stubbing unions

oi/type_graph/AddPadding.cpp, oi/type_graph/AddPadding.h, test/test_add_padding.cpp
- Pad classes with zero members
- Pad unions when necessary
=> AddPadding: Pad empty types as needed

oi/type_graph/AlignmentCalc.cpp, oi/type_graph/Types.h, test/TypeGraphParser.cpp, test/test_alignment_calc.cpp
- Recurse into params,parents,members,children of Classes
- Extend TypeGraphParser to understand bitfields
- Add tests
=> AlignmentCalc fixes

test/test_topo_sorter.cpp
=> TopoSorterTest: Add test for value template params

include/oi/oi-jit.h, include/oi/oi.h
Minor changes to header paths to work with our internal build.
- CI
=> Update internal build for oil v2

dev.oid.toml, oi/ContainerTypeEnum.h, oi/TreeBuilder.cpp, test/ci.oid.toml, test/integration/std_map_custom_comparator.toml, test/integration/std_multimap_custom_comparator.toml, test/integration/std_multiset_custom_comparator.toml, types/multi_map_type.toml, types/multi_set_type.toml, types/set_type.toml, types/std_map_type.toml
Implement Container V2 for std::multiset & std::multimap. Closes #313.
```
$ make test
```
=> Implement Container V2 for std::multiset & std::multimap

oi/IntrospectionResult.cpp, test/integration/std_optional.toml, test/integration/std_smart_ptr.toml, types/optional_type.toml, types/shrd_ptr_type.toml, types/uniq_ptr_type.toml
Implement Container V2 for smart pointers.
Closes #299 and #300.
```
$ make test
```
=> Implement Container V2 for smart pointers

test/integration/folly_f14_fast_map.toml, test/integration/folly_f14_node_map.toml, test/integration/folly_f14_vector_map.toml, test/integration/folly_shims.cpp, types/f14_fast_map.toml, types/f14_node_map.toml, types/f14_vector_map.toml
Implement Container V2 for `folly::F14VectorMap`.
Tests in `folly_f14_vector_map.toml` cover this implementation, but we'll have to wait for the CI to confirm they pass.
=> Implement Container V2 for F14Map

.circleci/config.yml, CMakeLists.txt, oi/OICodeGen.cpp, oi/OICompiler.cpp, oi/OICompiler.h, oi/OIGenerator.cpp, oi/OIGenerator.h, oi/type_graph/AddChildren.cpp, test/ci.oid.toml, test/integration/alignment.toml, test/integration_mttest.cpp, test/integration_sleepy.cpp, tools/OILGen.cpp
Summary: Update to clang-15 compiler and libraries as clang-12 is ancient.
Differential Revision: D46220858
=> Update to clang/llvm 15

README.md, website/docusaurus.config.js, website/static/CNAME
This updates the docusaurus config and adds the CNAME file for gh pages, then updates the readme to point at this domain.
Build website & serve it to ensure it works from the root.
```sh
cd website
yarn
yarn build
yarn serve
```
=> Use objectintrospection.org for the website

CMakeLists.txt, oi/PaddingHunter.cpp
It compiles on Arch, though there is one bigger change required to get msgpack 5 properly supported in CMake.
> Check that OI is working correctly, you can add some unit or integration test,
paste the output of some manual test, and / or paste the output of running
the test locally with `make test-static`
There is no such target `test-static`? `ctest` also doesn't seem to find anything? Am I missing something? I have these in my `CMakeCache.txt`:
```
BUILD_TESTING=ON
WITH_FLAKY_TESTS:BOOL=ON
WITH_TESTS:BOOL=ON
```
I added an `include(CTest)` to `test/CMakeLists.txt` and when I then run `ctest` I get tons of errors:
```
49% tests passed, 358 tests failed out of 702
Total Test time (real) =  93.14 sec
The following tests did not run:
61 - DrgnParserTest.StructAlignment (Skipped)
62 - …
```
=> Build system fixes

oi/OIDebugger.cpp, oi/OIDebugger.h, oi/Syscall.h
=> jitlog: use a memfd and glog

.circleci/config.yml, flake.lock, flake.nix
ci: move formatting checks to nix
=> ci: move formatting checks to nix

oi/type_graph/NameGen.cpp, test/integration/anonymous.toml, test/test_name_gen.cpp
=> NameGen: Override inputName for anonymous members

oi/type_graph/ClangTypeParser.cpp
tbv2: fix thrift isset with ClangTypeParser
Some of the logic that makes Thrift isset work for TreeBuilder-v2 in DrgnParser
(JIT OIL) wasn't ported to ClangTypeParser meaning it doesn't work in
Ahead-of-Time (AoT) OIL.
Add the template parameter name reconstruction for enum values to
ClangTypeParser.
Test plan:
- Tested with Thrift isset enabled on an internal type. Doesn't build before,
does build after.
=> tbv2: fix thrift isset with ClangTypeParser

oi/type_graph/AlignmentCalc.cpp, oi/type_graph/ClangTypeParser.cpp, test/test_alignment_calc.cpp
Summary: Correct identification of packing.
Differential Revision: D53815661
=> Correct packing calculation

oi/type_graph/ClangTypeParser.cpp
Ignores base classes which are virtual.
Cough.
=> ignore virtual base classes

oi/OICompiler.cpp
Summary:
The internal build is moving to LLVM-17 from LLVM-15. For our code there are two required changes to get it building: a header has been renamed and the signature of a function has changed.
Checked which LLVM major version these changes apply in and both are 16, macro gated accordingly so we maintain compatibility with both LLVM-15 and LLVM-17. Both versions build internally.
Differential Revision: D61268962
=> llvm: add support for LLVM16/17

flake.nix
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/519).
* #515
* __->__ #519
=> nix: split out devshells to allow adding extra packages
