facebookexperimental/object-introspection

website/docs/getting-started.md

Quick fix to clarify cmake build args
No testing `>:]`

Update suse instructions with non-static build args

---

website/docusaurus.config.js

Correct link to code to point to github
```
<a href="https://facebookexperimental.github.io/object-introspection/" target="_blank" rel="noopener noreferrer" class="footer__link-item">GitHub<svg width="13.5" height="13.5" aria-hidden="true" viewBox="0 0 24 24" class="iconExternalLink_nPIU"><path fill="currentColor" d="M21 13v10h-21v-19h12v2h-10v15h17v-8h2zm3-12h-10.988l4.035 4-6.977 7.07 2.828 2.828 6.977-7.07 4.125 4.172v-11z" style="--darkreader-inline-fill: currentColor;" data-darkreader-inline-fill=""></path></svg></a>
```
Is the generated code

Correct link to code to point to github

---

src/OIGenerator.cpp

Spotted a deprecation warning that I added about my code (whoops). Update `OIGenerator` from `codegen->generateFunctionsForTypesDrgn` to `codegen->generate`.
- CI

update to codegen->generate

---

src/FuncGen.cpp
src/FuncGen.h
src/OICodeGen.cpp

The container information added by `FuncGenInternal.h` has been made redundant by the pluggable containers feature. Remove this legacy difference.
- CI
- D42167455

remove funcgeninternal.h

---

src/ContainerInfo.cpp
src/ContainerInfo.h
src/OICodeGen.cpp
src/Serialize.h
types/caffe2_blob_type.toml
types/folly_iobuf_queue_type.toml
types/folly_iobuf_type.toml

Add the option to provide a custom regex in a container info file. This allows us to remove the hyper specific if conditions in the matching code, instead specifying them with their containers. In future it should also allow us to match multiple paths in the same container info file, reducing duplication.
- CI
This needs to go in after #7 else we'll fail to build, as that file doesn't have knowledge of the new `matcher` field.

container regex matching

---

.gitmodules

The extern repos are currently cloned with SSH. This means that attempting to clone them on a system that doesn't have an SSH key which GitHub accepts fails. Change them to HTTPS as they're read only in this context anyway.
Devserver:
- `cd /tmp && git clone https://github.com/JakeHillion/object-introspection.git oi && cd oi && git checkout https-submodules && ... && make test-devel`
NixOS (no SSH keys):
- `cd /tmp && git clone https://github.com/JakeHillion/object-introspection.git oi && mkdir oi/build && cd oi/build && cmake ..` - fails (unable to clone)
- `cd /tmp && git clone https://github.com/JakeHillion/object-introspection.git oi && mkdir oi/build && cd oi/build && git checkout https-submodules && cmake ..` - successfully clones
&& CI.

move extern repos to https addresses

---

src/OICodeGen.cpp
src/OICodeGen.h

Just doing some code review on OICodeGen* and picking up bits I see as I go along. It's mostly minor stuff here and is mainly composed of:
- Removing 'struct' keyword from a bunch of declarations - this is C++ and not C.
- Converting a bunch of dragon error handling cases to use if initializer constructs. Just keeps thing a bit cleaner. Also added in calls to drgn_error_destroy() where missing.
- Some heavy string generation for debug is called in the when debugging is not enabled (glog) so blocked it with a VLOG_IS_ON() macro. 
- Also changed pretty much all postfix increments on for loops. It doesn't actually matter but it's generally accepted to use prefix unless there is an explicit reason and I can't see that there are any in these instances.
CI passes all tests.

Codegen review changes

---

test/integration/anonymous.toml
test/integration/cycles.toml
test/integration/gen_tests.py
test/integration/ignored.toml
test/integration/multi_arg.toml
test/integration/pointers.toml
test/integration/pointers_function.toml
test/integration/pointers_incomplete.toml
test/integration/references.toml
test/integration/std_smart_ptr.toml
test/integration/std_unordered_map.toml
test/integration/std_vector.toml

This change better documents and tracks our skipped tests.
- Add `oil_disable` and `oid_disable` for cases where a test only makes sense for one part of the software. Specifically, any test with `--chase-raw-pointers` can be `oil_disable` as it will never make sense under OIL - it is not a bug like a skipped test.
- Enable void smart pointer present tests.
- These tests were disabled as they don't track the dynamic size. However, I don't think there is a dynamic size as the void pointer could contain an object of any size and we have no way of knowing it. Therefore, treat the current behaviour of reporting the dynamic size as 0 as correct.
- There are a set of tests in `pointers_incomplete` that codegen under OIL but not OID. Replace the general `skip` with an `oid_skip` to account for …

Skipped test cleanup

---

CMakeLists.txt

This change removes the post build `sudo setcap` step on oid. This enables building in environments which don't have root (e.g. constrained build environments such as `nix`).
- I ran `mttest2` as my user then ran `oid` against it, and it worked fine.
- The version of `mttest2` running as `root` did not attach unless I used `sudo`.
- The version we use in production doesn't have this capability.
- `make clean && make test-devel`

remove setcap

---

CMakeLists.txt

We currently forcibly build `drgn` with `-march=broadwell` and `-O3`. The architecture is particularly bad as it stops us building on more limited architectures, such as a no additional features x86_64 VM. Remove the optimisations too as this should be protected behind a flag and we have a different optimised internal build anyway.
Closes #24 
- `make clean && make test-devel`
- CI

Stop over optimising drgn

---

tools/OILGen.cpp

`oilgen` always uses drgn type iterators but doesn't enable them by itself. Change this so an external environment variable doesn't have to be set.
- CI

oilgen: set DRGN_ENABLE_TYPE_ITERATOR

---

src/OIDebugger.cpp
test/integration/CMakeLists.txt
test/integration/std_multimap_custom_comparator.toml
types/multi_map_type.toml

A std::multimap which provides a comparator template parameter caused oid to have a number of issues which resulted in failure to codegen (static_asserts in stl headers mainly). This change to the multipmap type definition simply aligns it with the std::map definition by substituting a custom definition for the provided template parameters via config.
I've added a multimap test that provides a comparator. No other test failures occur with this change.

Support std::multimap with comparator template parameter

---

CMakeLists.txt

Allows us to use the open source CMakeLists.txt without modification for internal builds with custom environment variables.

Add CMake hook for defining custom build rules

---

types/small_vec_type.toml

Folly updated the signature of small vec types here: https://github.com/facebook/folly/commit/c0a4e11b31ec35ca7506a2e1666f45db63fd3ef0
I needed to add a new 'using' for policy_size_type, as this is commonly used with this new template parameter.
I'm struggling a bit getting the tests to run locally, so I'll just have CI run it for now.

Update small vec types to reflect folly update

---

examples/compile-time-oil/OilVectorOfStrings.cpp
include/ObjectIntrospection.h
src/FuncGen.cpp
src/FuncGen.h
src/OICodeGen.cpp
src/OILibrary.cpp
src/OILibraryImpl.cpp
test/integration/gen_tests.py

Make a couple of changes to the OIL interface.
- `#ifdef` away the JIT functions which you shouldn't call in compile time mode. They wouldn't work with the header only library (linker failures) but this avoids confusion.
- Change from pointers to references. This is a major change to the API, but they shouldn't have been pointers in the first place as they're always expected to be valid. Bite the bullet now and swap them before we have major consumers.
- CI
- `make test-devel` after each commit
- Manually checked the compile time example after each commit

Oil interface cleanup

---

include/ObjectIntrospection.h
src/DrgnUtils.cpp
src/DrgnUtils.h
src/OIGenerator.cpp
src/OIGenerator.h

Although the existing weak symbol implementation works well in the context it was tested in, it doesn't work well in the static library context. Switch to an impl weak symbol which has no default implementation and check that in the library.
- CI
- `cd examples/compile-time-oil/ && make && ./OilVectorOfStrings`

oil: switch to using an impl function with no default implementation

---

.circleci/config.yml

This will give us more flexibility later, e.g. allowing different steps for GCC and Clang (as needed for code coverage), or letting us parallelise our tests across multiple machines.

CI: Split build and test into separate jobs

---

.circleci/config.yml

CI: Parallelise tests
This reduces the time to run tests from 5-9 minutes down to 3-4 minutes.
`nproc` is returning `1` on the CI node which is processing our
config.yml. In the absense of a better way of getting the number of CPUs
on our executor, just hardcode it.
We actually have 16 cores on our 2xlarge executors, but higher
parallelism in tests appears to cause oid to sometimes fail with SIGILL.
I'm still investigating this problem.

Parallel tests

---

src/OIDebugger.cpp

Remove extra "0x" prefix when logging addresses
Force SIGILL log. Note the double "0x0x" before this patch.
Before this patch:
`OOPS! SIGILL received for pid 4002 addr: 0x0x7fe16ccfe040`
After this patch:
`OOPS! SIGILL received for pid 3683 addr: 0x7f1c8e0af040`

OIDebugger: Remove extra "0x" prefix when logging addresses

---

.circleci/config.yml
CMakeLists.txt

CI: Add code coverage reporting
Add CODE_COVERAGE option to enable coverage instrumentation in builds.
Add new CI job to upload coverage reports to CodeCov.io.
Reports can be found by navigating the codecov.io UI, or by going to
the URL printed at the end of the "Code Coverage" CI job. More CodeCov
integration could be set up later once we have coverage reporting on the
main branch.

Code Coverage

---

.circleci/config.yml

Apparently this is needed for CodeCov.io to work.
Without this patch, no coverage available:
https://app.codecov.io/github/facebookexperimental/object-introspection/commit/208aac162854b98cbcd1734a4d1efed268e0db33
With this patch, coverage available:
https://app.codecov.io/github/facebookexperimental/object-introspection/commit/f9dec417d7b107735d537245a098c3fd23f58ebd

Code coverage: Checkout repo before running

---

test/integration/inheritance_polymorphic.toml
test/integration/inheritance_polymorphic_diamond.toml
test/integration/inheritance_polymorphic_non_dynamic_base.toml

These tests trigger the `-Wnon-virtual-dtor` warning which we have enabled internally. I added virtual destructors to make these tests happy.
- CI

add missing virtual destructors

---

examples/compile-time-oil/Makefile
src/OIGenerator.cpp
src/OIGenerator.h
tools/OILGen.cpp

Add an `--exit-code` option to oilgen which causes it to return a bad exit code if no code is generated. We won't generally use this as no generation isn't necessarily a failure, but it's useful for testing.
- CI
- `cd examples/compile-time-oil && make`
- Removed the OIL call and checked this fails.

oilgen: add an --exit-code option to fail on noop

---

include/ObjectIntrospection.h
src/FuncGen.cpp

Two things:
- Make `getObjectSize` noinline - this causes issues with higher optimisation levels.
- Set `ObjectSize` to 0 before starting counting into it. Whoops.
- `cd examples/compile-time-oil && make && ./OilVectorOfStrings`
- CI

Oilgen fixes

---

src/OICodeGen.cpp
types/sorted_vec_set_type.toml

This change corrects how we handle folly::sorted_vector_set handling and adds another space into the codegen comments (so you can easily cut'n'paste the symbol without picking up the trailing slash).
I have logged task #62 as this change doesn't contain a test for this container and we need one.
'make test-devel` passes all tests. The integration tests are failing for me currently but it's not owing to anything here (I think!).

Fix folly::sorted_vector_set and minor codegen comment change

---

.circleci/config.yml

The CI SIGILL failures (#59) have become more common as we've increased the number of tests. Double the the 'repeat-until-pass' number from 2 to 4 to vastly decrease the likelihood of this hitting the top level signal - it should be around 200000x less likely.
CI

ci: bump repeat-until-pass to 4

---

src/OICodeGen.cpp
src/OICodeGen.h
types/sorted_vec_set_type.toml

When verbose logging is enabled (level 2 and above) we generate a huge amount of debug and a lot of it is coming from the printTypePath() function which is called when we enumerate types. This code iterates over all the known types and prints the name out which generates a lot of noise and makes it more difficult to figure out what is going off.
I've spoken to @arsarwade and he is going to rewrite the debugging code in codegen at some point. In the meantime I'm just removing this before I lose my mind.
`make test-devel`works with no new failures.

Remove type path printing debug code 

---

src/OICompiler.cpp

`ManifoldCache.h` is included but unused in `OICompiler.cpp`. This makes it difficult to split up the exposed targets which require it and the targets that don't. Remove this unused include.
- CI
- D43187545

remove unused ManifoldCache.h from OICompiler

---

src/OILibraryImpl.cpp
src/OILibraryImpl.h

Removes an unused cache object from `OILibraryImpl`. This removes the dependency on caching which removes the dependency on internal FB stuff from JIT OIL, massively reducing debug bloat.
- CI
- D43239161

oil: removed unused cache in OILibrary

---

CMakeLists.txt

We are already using CMP0109 which depends on 3.19. This change just provides more useful error messages when using older versions.

Bump minimum CMake version to 3.19

---

types/sorted_vec_set_type.toml

The changes in #63 makes us treat a folly::sorted_vector_set as a container adaptor. We also need to remove the configuration which specifies the number of template parameters as container adaptors shouldn't enumerate their template parameters. Guess I should also do issue #62 ...
Tested on an application using a sorted_vector_map and all is now good.

Stop enumerating template params for sorted_vector_set

---

src/OICompiler.cpp
test/integration/primitives.toml

This is a distinct primitive type according to https://en.cppreference.com/w/cpp/language/types
Now all primitive types are tested.

integration/primitives.toml: Add char8_t test

---

src/OICodeGen.cpp

A '`conditional_t` type's name will often contain conditional expressions so we need to special case this as it causes problems when removing namespaces.
This change fixes issues with volume testing that were being encountered. Current tests have no new failures. A new test needs to be added to include `conditional_t` types (see issue #76 ).

Special case conditional_t type name handling

---

src/OIGenerator.cpp

Checks a call for `drgn_type_name` which was asserted on `drgn_type_has_name`.
- CI

oilgen: add check for drgn_type_has_name

---

test/integration/CMakeLists.txt
test/integration/std_conditional.toml

Add a test for verifying OI processes a `std::conditional_t` type. This addresses issue #76 .
Test passes in test suite:
```
61/379 Test  #99: OidIntegration.std_conditional_a .......................................   Passed    5.01 sec
```

add std::conditional test

---

src/TreeBuilder.cpp

- Update rocksdb to [v7.9.2](https://github.com/facebook/rocksdb/releases/tag/v7.9.2).
- Add an additional header dependency on `"rocksdb/statistics.h" for upcoming rocksdb 8.
- CI

Update rocksdb to 7.9.2

---

src/OIDebugger.cpp
src/OIDebugger.h
src/X86InstDefs.h

The OI code prologue is a 64 byte area used to setup a call into JIT code and a subsequent return back to OI via an `int3`. Currently we have 23 bytes of useful instructions and we pad the rest with `nop` instructions (single byte `0x90` opcode) which, in hindsight, turns out to be suboptimal. If, for some reason, we end up executing instructions past the `int3` then the thread will execute the nops and run into some variables that we have just after the prologue (starting with the `dataBase` variable which is a pointer to the current byte of data being written by JIT code ). Depending on it's current value this will either be a random sequence of junk instructions or an illegal instruction.
A much better approach is to replace the `nop` instructions with `ud2` instructions (a `ud2` is …

Replace nop instructions with ud2

---

test/integration/CMakeLists.txt
test/integration/gen_tests.py
test/integration/runner_common.cpp
test/integration/runner_common.h

As config files may contain paths relative to them, copying them into an arbitrary location (tmp path) won't succeed. Due to the directory layout this works in OSS & CI, but it failed when the tests were brought over internally. Canonicalise the paths while copying the config file to prevent this issue.
It became clear while testing this that the tests in `ignored.toml` weren't being run. Added them to the `test/integration/CMakeLists.txt` test cases and fixed them working with OIL.
Closes #55 
- D43647536
- CI

tests:  make relative config paths absolute when copying

---

.circleci/config.yml
src/OIDebugger.cpp

The CI has been experiencing failed tests owing to targets dying with SIGILL delivery and as far as I know we've never seen this in production which always seemed odd. The reason is that we have a race condition in processTraps() that becomes more reproducible as the JIT code get smaller (quicker to execute).
The race is between when we continue a target thread to execute the JIT code (the ptrace(PTRACE_CONT) at the bottom of processTraps()) and waiting for that thread to finish JIT code execution - to execute the int3 instruction and the subsequent SIGTRAP that is raised to oid which we receive by the waitpid() call at the start of processTrap().
The VLOG() calls being executed at the start of processTraps() and the ptrace(PTRACE_CONT) give a window where we are not waiting for signals …

reduce race window for breakpoint trap in prologue

---

examples/compile-time-oil/.gitignore
examples/compile-time-oil/Makefile
src/OIGenerator.cpp
src/OIGenerator.h
tools/OILGen.cpp

Puts some temporary rubbish in the OILgen path to generate multiple output `.o` files from a single `.o` file. This occurs when there are multiple OIL calls in a single compilation unit.
Eventually (classic) this will be replaced with a single `.o` file containing both calls. This is more optimal as we can share the anonymous namespace between them, e.g. if we have `struct A {}; struct B { A a; };` and have OIL calls for both we can reuse the logic for traversing `A` when traversing `B`. Although this would be possible to implement now, it should be significantly easier after Type Graph is implemented, so I'm using this simple solution for now.
- `cd examples/compile-time-oil && make && ./OilVectorOfStrings` - works
- D43875626
- CI

oilgen: change interface to support multiple calls in one cu

---

CMakeLists.txt
src/CMakeLists.txt
src/DrgnUtils.cpp
src/DrgnUtils.h
src/OICodeGen.cpp
src/OICodeGen.h
src/OIUtils.h
src/Serialize.cpp
src/SymbolService.cpp
src/TreeBuilder.cpp

Split codegen into separate build targets
To help with the transition to type-graph based CodeGen, we need to
reduce dependencies on legacy CodeGen from other parts of OI.
Pieces of CodeGen referenced by other files, but which only return
drgn data have been moved into a new "drgn_utils" target, allowing
us to remove CodeGen dependencies for these functions.
The new "symbol_service" build target can be used in the future by
other files only needing access to symbol information and not full
CodeGen.

Split codegen into separate build targets

---

src/FuncGen.cpp
src/FuncGen.h

This will make it easier to share between legacy and TypeGraph codegen.

FuncGen: Make functions static where possible

---

src/TreeBuilder.cpp
src/TreeBuilder.h
test/integration/anonymous.toml
test/integration/pointers.toml
test/integration/sorted_vector_set.toml
test/integration/std_array.toml
test/integration/std_optional.toml
test/integration/std_smart_ptr.toml
test/integration/std_string.toml
test/integration/std_variant.toml
test/integration/std_vector.toml

Add initial pass for exclusive size
Unfortunately this became a lot more complex than I was hoping - I was trying to avoid making additional calls into rocksdb, so I couldn't just query for members. That said, it's not that bad considering I had to touch a lot of places.
Writing tests to hopefully cover all the edge cases I can think of.

Add support for exclusive size reporting

---

src/Metrics.h
test/integration/arrays.toml
test/integration/gen_tests.py

- Disables warnings for test code where they're reasonable.
- Changed something which used bitfields with a default initialiser in our single C++17 file to using whole bools with a default initialiser.
I gave up on turning on `-Werror` because I am weak. Before we turn this on we need to build a consistent set of warnings in all the different build environments, otherwise it's very annoying.
- `make test-devel` - there are fewer warnings.
- CI

Warnings cleanup

---

include/ObjectIntrospection.h
src/OILibrary.cpp
src/OILibraryImpl.cpp
src/OILibraryImpl.h
test/integration/gen_tests.py

5 of the fields in the OIL options relate to caching and JIT compilation. Remove these as they don't make sense anymore - you should use compile time OIL if you want caching and to disable JIT. These options are not used under compile time OIL.
- CI
- D44216203

oil: remove fields in options

---

test/integration/gen_tests.py
test/integration/runner_common.cpp

Instead of using an environment variable, pass the path to the config
file as a command line argument. This makes it possible to directly
copy the command being run (as show with --verbose) and run it in a
debugger outside of the test framework.
Old verbose output:
```
Running: /home/ajor/src/object-introspection3/build/test/integration/integration_test_target oil cycles_unique_ptr
```
New verbose output:
```
Running: /home/ajor/src/object-introspection3/build/test/integration/integration_test_target oil cycles_unique_ptr /home/ajor/src/object-introspection3/build/testing.oid.toml
```

Integration tests: Pass config to OIL tests on the command line

---

types/std_variant.toml

`getSizeType` for `std::variant` previously used a custom templated visitor. Update to use `std::visit`. This is a `.toml` only change as the data written to the data segment is identical.
`if (container.index() >= sizeof...(Types))` is necessary as `container.valueless_by_exception()` does not work correctly for variants whose index is optimised to a type which can't contain `0xffffffffffffffff`. There is already a test that checks the last possible element is handled correctly.
- CI

std::variant: change to use std::visit

---

src/OID.cpp
src/OIDebugger.h

Quit oid if cache is not fully configured. I've tested both sides of this if statement manually internally, and with --mode prod, to make sure other cases are not affected.

Quit oid when upload/download is requested but cache is disabled

---

dev.oid.toml
src/ContainerInfo.h
src/OICodeGen.cpp
src/TreeBuilder.cpp
test/ci.oid.toml
test/integration/std_smart_ptr.toml
types/weak_ptr_type.toml

Previously, we treated weak_ptrs as normal types and we recursed within them, following the internal data pointer and possibly causing crashes. We really shouldn't be following them, so I added a custom type to simply abort processing. If we want to handle them (ie: check if they are valid, and follow them if so), that should be fairly easy with the work there is here so far.
If people think we should be following weak pointers, I'm happy to add that in.
Added test cases, and manual testing on a couple types (verifying the json output).

Avoid following weak_ptrs

---

.gitmodules

Add drgn function for looking up by "pure name"
Normally we really shouldn't need to go from string name to type, but in theory it is possible and quick with drgn to do so. Unfortunately doing so properly would require making a parser which can consume C++ types and return "normalized" versions of that. In lieu of doing that, I'm just doing a simple string split. 
Therefore this API should work for the simple case (no spaces, types matching dwarf exactly, etc). But if anything is wrong, we will return not found.
Add call to this function and verify build succeeds (to make sure we can actually call this function). Verify function works with a hacky python wrapper on a larger binary. Also tested by Jon as part of volume testing.

Add drgn function for looking up by "pure name"

---

test/integration/cycles.toml

uint64_t is a typedef. int is a primitive.
The cycles tests are going to be re-used to underpin some type-graph unit tests. The patch removes unnecessary typedefs and makes the unit tests simpler.

Integration tests: Remove typedefs from cycles.toml

---

src/Common.h
src/ContainerInfo.cpp
src/ContainerInfo.h
src/FuncGen.cpp
src/FuncGen.h
src/OICodeGen.cpp
src/OICodeGen.h
src/Serialize.cpp
src/Serialize.h
src/TreeBuilder.cpp
tools/OIP.cpp

Code generation of container function declarations and definitions currently runs through two maps, `typeToDeclMap` and `typeToFuncMap`. These are indexed by the `ContainerTypeEnum` which comes from a field in `ContainerInfo`. Rather than having this indirection, we should get the `decl` and `func` directly from the `ContainerInfo` object.
- Delete the `ContainerInfo` copy constructor as it now contains potentially very large strings.
- Change all copies of `ContainerInfo` to a reference to `OICodegen`'s `containerInfoList`.
- Remove `ContainerInfo` from `Serialize.h` as we no longer need to serialize it - only the numeric enum passes between `OICodeGen` and `TreeBuilder`, which makes sense!
Specifically, instead of looking up `typeToDeclMap[cinfo.ctype]` we now use `cInfo.codegen.decl` …

codegen: carry decl and func with containerinfo

---

src/OIGenerator.cpp

Fix a warning in the pure changes I added last week. Whoops, butterfingers :)
All this should be is a missing declaration in `libdrgn/dwarf_info.h`
These are now the warnings left in the drgn codebase on our fork
```
../../libdrgn/dwarf_info.c: In function ‘drgn_func_iterator_create’:
../../libdrgn/dwarf_info.c:9434:7: warning: assignment to ‘struct drgn_func_iterator *’ from incompatible pointer type ‘struct drgn_type_iterator *’ [-Wincompatible-pointer-types]
*ret = iter;
^
../../libdrgn/dwarf_info.c: In function ‘drgn_type_linkage_name’:
../../libdrgn/dwarf_info.c:9585:11: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
*str_ret = dwarf_formstring(&linkage_name);
```
Which should be fixed probably, but not right now.

Fix warning in drgn pure name changes

---

.circleci/config.yml
test/integration/CMakeLists.txt
test/integration/fbstring.toml
types/fb_string_type.toml

Adds a test case for `folly::fbstring`. Leaves the shared case skipped as it's not including the string allocation.
- `make configure-devel && make test`
- CI

add test for folly::fbstring

---

src/OICodeGen.cpp

Makes the offset printing in generated code correct which was confusing.
For a simple struct definition:
```
struct A {
int foo;
int bar;
};
```
Before:
```
struct A{
/* 4         |     4 */ int foo;
/* 8         |     4 */ int bar;
};
```
After:
```
struct A {
/* 0         |     4 */ int foo;
/* 4         |     4 */ int bar;
};
```

fix offset in generated code

---

test/integration/CMakeLists.txt
test/integration/folly_shims.cpp

This fixes linker errors in debug builds.
When building in debug mode (-DCMAKE_BUILD_TYPE=Debug), folly requires the function "safe_assert_terminate" to be defined. To avoid building and linking against folly, we define our own no-op version of this function.

Add folly shims to avoid linking against folly

---

.circleci/config.yml

CodeCov's docs say that a token isn't required for a public repository, but our uploads have been broken for a few weeks at this point and passing in the token fixes them...

Pass in CodeCov.io token through CI env var

---

examples/compile-time-oil/Makefile
src/CMakeLists.txt
src/Features.cpp
src/Features.h
src/OICodeGen.cpp
src/OICodeGen.h
src/OID.cpp
src/OIDebugger.cpp
src/OIDebugger.h
src/OIGenerator.cpp
src/OILibraryImpl.cpp
src/OIUtils.cpp
src/OIUtils.h
src/TreeBuilder.cpp
src/TreeBuilder.h
test/integration/gen_tests.py
test/integration/ignored.toml
test/integration/inheritance_polymorphic.toml
test/integration/pointers.toml
test/integration/runner_common.cpp
test/integration/runner_common.h
test/integration/thrift_isset.toml
tools/OITB.cpp

Adds features which are specified either on the command line or the config.
- Enable a feature with e.g. `-fchase-raw-pointers`.
- Disable a feature with e.g. `-Fchase-raw-pointers`, last on the command line is always preferred.
- Add a base set of features in the config using: `features = ["chase-raw-pointers"]`.
- Messed around with the test extra config option as sometimes with `.toml` things need to be at the top or at the bottom of the file.
- New tests for each case.
- Checked `oilgen` still functions on its limited test case (really should write proper external tests for that...).
- `make test`
- CI

Add a feature system to OI to make it easier to add optional features in the future

---

src/Common.h
src/SymbolService.cpp
src/SymbolService.h

SymbolService is used to locate symbols when the JIT code is being relocated in the target process. Our previous implementation was inefficient, as a new `Dwfl` instance was created, initialised with the target's modules, then destroyed, for each call to `locateSymbol`.
This PR modifies SymbolService to keep the same `Dwfl` instance across multiple calls to `locateSymbol`. Dwfl is initialised once, during the SymbolService construction.
This PR doesn't change `oid`'s behaviour. The tests should be enough to validate the changes.
```
$ make test
[...]
100% tests passed, 0 tests failed out of 420
Total Test time (real) =  66.51 sec
```

Faster locateSymbol by re-using dwfl across calls

---

.gitmodules

What it says on the tin. Update vendored elfutils within our vendored drgn to 0.189, restacking the two changes on top of it. Moves the elfutils vendoring commit to the bottom of our drgn stack (it was 7th I think) so all of our custom commits use it.
- `make test`
- CI

drgn: revendor elfutils at 0.189

---

oi/SymbolService.cpp

This is a brutal change to the drgn fork, getting it ready for a rebase. Mainly:
- Removes commits of already dead code.
- Squashes fixes to earlier commits into the earlier commit, hopefully making each commit valid in isolation.
- Disables function inlining and the drgn infrastructure. It's not widely used, and we can cherry-pick it back if it becomes of interest in the future.
All in all this gets us down to 26 commits ahead, and the majority are neat and self contained. 2 are already upstreamed and 1 will be worked on soon.
- `make test`
- CI

drgn: refactor, cull dead code, and disable inline

---

CMakeLists.txt
oi/Headers.h
oi/OIDebugger.cpp
oi/OIGenerator.cpp
oi/OILibraryImpl.cpp
oi/OITraceCode.cpp
resources/CMakeLists.txt

Previously we had an `R"(` string in `OITraceCode.cpp` which allowed us to include the file as a string. Instead, keep `OITraceCode.cpp` a fully formed C++ file and utilise the build system to turn it into a string. This will be used for more header files that are needed both as valid headers and as strings for JIT compilation in the Typed TreeBuilder work.
- `make test`
- CI

resources: manage headers properly

---

oi/Features.cpp
oi/Features.h
oi/OICodeGen.cpp
oi/OICodeGen.h
oi/OIDebugger.cpp
oi/OIUtils.cpp
oi/OIUtils.h
oi/TreeBuilder.cpp
oi/TreeBuilder.h
tools/OITB.cpp

Features were implemented as a `std::set` and cached as bits. Make this more efficient by storing them in a `bitset` (wrapped to have enum accessor).
- `make test`
- CI

features: switch to bitset

---

test/integration/CMakeLists.txt
test/integration/alignment.toml
test/integration/gen_tests.py

More prep-work for TypeGraph, but useful in general and found a new bug: #143.
Also update the test framework so that OIL tests assume a dynamicSize of 0 when none is explicitly set. This just makes it a little easier to write tests for static types.

Add Alignment Tests

---

oi/OID.cpp

It was previously easy to miss modules and I haven't been able to notice any difference in behaviour when setting the VLOG level globally (despite what the old comment says).

OID: Set glog VLOG level globally for all modules

---

oi/DrgnUtils.cpp
oi/DrgnUtils.h
oi/OICodeGen.cpp
oi/OICodeGen.h

These functions are intended to be shared between OICodeGen and TypeGraph CodeGen.

DrgnUtils: Add isSizeComplete and underlyingType helper functions

---

.circleci/config.yml

The "src" directory got renamed to "oi" and the previous rule stopped matching our source code. By changing to collect coverage for everything except for "build" and "extern", we should avoid this problem in the future.

CodeCov: Collect coverage from all source files

---

oi/CMakeLists.txt
oi/ContainerInfo.cpp
oi/OIUtils.cpp
oi/support/Toml.cpp
oi/support/Toml.h
test/integration/CMakeLists.txt
test/integration/runner_common.cpp

`tomlplusplus` defaults to header-only but this is inefficient when you include it in multiple places (which we do). Explicitly compile the header in a single translation unit to improve compilation performance.
- `make test` - an `integration_py` failure because some static size is 16 off. This has to be unrelated.
- CI
- Hoping it's quicker. Testing is hard.

tomlplusplus: compile header once

---

oi/CMakeLists.txt
oi/CodeGen.cpp
oi/CodeGen.h
oi/Features.h
oi/OIDebugger.cpp
test/test_codegen.cpp

This code mostly works, but is obviously not complete. This commit just adds the code and tests, but does not enable it in OID or OIL.
All integration tests pass when running against legacy OICodeGen
82% of OidIntegration tests pass when running against TypeGraph CodeGen

TypeGraph: Add new CodeGen

---

dev.oid.toml
oi/Common.h
oi/TreeBuilder.cpp
test/ci.oid.toml
types/cxx11_string_type.toml
types/std_char_traits.toml
types/string_type.toml
types/thrift_isset_type.toml

std::basic_string takes three template parameters:
1. CharT
2. Traits
3. Allocator
The Traits parameter was causing issues, as it requires a type which exposes certain things, e.g. `Traits::value_type`.
We have a few options to resolve this:
1. Remove this parameter, as we do for allocators
Cons: removing a template parameter doesn't work if other parameters appear after it
2. Stub this parameter, as we do for hashers/comparators
Cons: we need to hardcode an implementation that satisfies the `Traits::value_type` requirements
3. Leave the parameter as-is
Cons: will not work if a non-standard Traits is used
By using the real implementation of this Traits parameter
(normally `std::char_traits<CharT>`), we get one that we know will
work as long as it is defined in a stdlib header.
Option 3 is …

TypeGraph: Fix std::string container

---

oi/type_graph/NameGen.cpp
oi/type_graph/NameGen.h
oi/type_graph/Types.h
test/test_name_gen.cpp

This fixes the test failure for std::conditional_t
The following test now passes with and without type graph:
```
OidIntegration.std_conditional_a
```

TypeGraph: Handle alias templates

---

oi/CodeGen.cpp
oi/TreeBuilder.cpp
test/integration/arrays.toml

Multi dimensional arrays are not flattened into 1-D arrays when using TypeGraph. Update TreeBuilder to account for this.
By not flattening arrays, we are able to produce more descriptive results.
The disadvantage is that we must now recurse inside arrays containing only primitives. A better solution to requiring flattening would be the planned work to not recurse into any static types (not just primitives). This would also apply to multi-dimensional arrays of primtivies.
The following test now passes with and without TypeGraph:
```
OidIntegration.arrays_multidim
```

TypeGraph: Fix multi dimensional arrays

---

oi/CodeGen.cpp
oi/type_graph/AddPadding.h
oi/type_graph/CMakeLists.txt
oi/type_graph/RemoveIgnored.cpp
oi/type_graph/RemoveIgnored.h
test/CMakeLists.txt
test/test_add_padding.cpp
test/test_remove_ignored.cpp

100% of integration tests pass with legacy OICodeGen
86% of integration tests pass with TypeGraph CodeGen (no new failures)
This previously failing test now passes:
```
OidIntegration.ignored_a
```

TypeGraph: Respect [[codegen.ignore]] config value

---

oi/CMakeLists.txt
oi/ContainerInfo.h
oi/ContainerTypeEnum.h
oi/OICodeGen.h
oi/OIDebugger.cpp
oi/Serialize.h
oi/SymbolService.cpp
oi/SymbolService.h
oi/TreeBuilder.h
oi/TypeHierarchy.h
oi/type_graph/AddChildren.cpp
oi/type_graph/AddChildren.h
oi/type_graph/DrgnParser.cpp
oi/type_graph/DrgnParser.h
tools/OITB.cpp

`Common.h` is used in several places and includes the massive `drgn` header. Split it up for better dependencies.
- `make clobber; make configure-devel && make test'
- CI

clean up common.h

---

oi/DrgnUtils.cpp

Ensure type->_private->oi_name is never a null pointer. We just assign it an empty string if the type has no tag or if the tag is null.
A `make test` was clean.

ensure oi_name is never a nullptr

---

oi/OICodeGen.cpp

Fix a path where `oi_name` is left as a nonsense pointer rather than nullptr.

set function oi_name to null rather than garbage

---

oi/Headers.h
oi/OITraceCode.cpp

Meta's Open Source Team's automated checks highlighted the missing copyright headers on Headers.cpp.
We had a manual exclusion rule on OITraceCode.cpp, but seeing as how we have core code in this file, I added the header to it and removed the exclusion rule.

Add copyright header to all source files

---

CMakeLists.txt
tools/OIP.cpp
tools/OIRP.cpp
tools/OITB.cpp

Fixes & QoL:
* OIP: Fix TypeHierarchy deserialisation
* OIP: Print 'this' as an argument for methods
* OIP: Print location expressions of arguments
* OITB: Add support for -f/-F feature flags
Also introduce the new tool `oirp` to read the content of OID's output RocksDB.
No change to `oid`.
```
$ make test
...
99% tests passed, 1 tests failed out of 572
Total Test time (real) = 180.18 sec
...
The following tests FAILED:
112 - integration_py (Timeout)
```

Tooling improvements

---

oi/OID.cpp
test/integration/README.md
test/integration/anonymous.toml
test/integration/cycles.toml
test/integration/inheritance_polymorphic.toml
test/integration/inheritance_polymorphic_diamond.toml
test/integration/inheritance_polymorphic_non_dynamic_base.toml
test/integration/pointers.toml
test/integration/pointers_function.toml
test/integration/pointers_incomplete.toml
test/integration/std_smart_ptr.toml
test/integration/thrift_isset.toml
test/integration/thrift_isset_missing.toml
tools/OITB.cpp

The Features change added a new system of feature flags that don't have a distinct command line argument each. This removes the old flags in favour of the new system.
- `make test`
- CI

features: clean up old flags

---

.circleci/config.yml

The C++ compiler generates implicit branches for exception handling,
which is particularly common when calling standard library functions.
It's not generally useful to have tests for the case when
std::vector::push_back fails due to an out-of-memory condition, so in
this PR we use a feature in the latest lcov release to filter out these
compiler-generated branches.
Our code coverage numbers consequently go way up!
(The Codecov bot's comment has not updated to reflect the latest version of this PR - click through to see the real numbers)

Code Coverage: Reduce irrelevant partial branch matches

---

oi/CMakeLists.txt
oi/CodeGen.cpp
oi/CodeGen.h
oi/ContainerInfo.cpp
oi/ContainerInfo.h
oi/OIDebugger.cpp
oi/SymbolService.h
test/CMakeLists.txt
test/mocks.h
test/test_codegen.cpp
test/type_graph_utils.cpp
test/type_graph_utils.h

Add a first test for TypeGraph CodeGen.
This required some refactoring of CodeGen to make it unit-testable.

CodeGen unit tests

---

oi/type_graph/PassManager.cpp
oi/type_graph/Printer.cpp
oi/type_graph/Printer.h
oi/type_graph/TypeGraph.h
test/test_add_padding.cpp
test/test_drgn_parser.cpp
test/test_flattener.cpp
test/test_remove_ignored.cpp
test/test_remove_top_level_pointer.cpp
test/test_type_identifier.cpp
test/type_graph_utils.cpp

- Don't truncate output above 30k characters
- Include enough padding at the begining of lines to account for large node IDs
Before:
```
[1070]                       Class: ClassName
Param                                                                                                                                                                                                                                                                                                          
Enum: ParamName (size: 4)
```
After:
```
[1070]                       Class: ClassName
Param …
```

Printer: Improvements for displaying large type graphs

---

oi/type_graph/NameGen.cpp
test/test_name_gen.cpp

Previously we always deleted the last two characters and appended a `>`.
Old:
```
MyContaine>
```
New:
```
MyContainer
```

NameGen: Handle containers with zero template params

---

oi/Features.h
oi/OICompiler.cpp
oi/OICompiler.h
oi/OID.cpp
oi/OIDebugger.h
oi/OILibraryImpl.cpp

Passes through the generate JIT debug info option to OICompiler as part of the feature set rather than as a separate flag. This will ensure it builds a different cache in remote builds, and allows other features to affect the compilation in future.
- `[]: make test: 100% tests passed, 0 tests failed out of 577`
- `["-fgen-jit-debug"]: make test: 100% tests passed, 0 tests failed out of 577`
off:
```
size -A /tmp/oid-integration-sMsGIK/*.o
/tmp/oid-integration-sMsGIK/1748082814871496692.o  :
section              size   addr
.text                 855      0
.bss              1048593      0
.rodata.str1.1         33      0
.rodata.str1.16        17      0
.comment              113      0
.note.GNU-stack         0      0
.eh_frame             144      0
Total             1049755
```
on:
```
$ …
```

features: add GenJitDebug

---

oi/CodeGen.cpp
oi/Features.h
oi/OICodeGen.cpp
oi/OID.cpp
oi/OIDebugger.cpp
oi/OIDebugger.h

Convert jit-logging to be a feature flag. This removes the `-l` option and adds a `jit-logging` feature flag. This also means that when jit logging is not enabled the JLOG* macros generate nothing so we remove all the extraneous branching.
No new test regressions in the test suite.
I manually ran oid with the current codegen implementation against a test binary (an old version of mttest <sigh>) and the number of instructions generated for the main text segment was 1251 with jit-logging enabled and 885 without (default). Previously this would have been 1251 instructions in both.
I also ran the same oid invocations but with the type-graph implementation (-ftype-graph) and it produced the same results.

feature flag jit-logging

---

.circleci/config.yml
test/integration/README.md
test/integration/runner_common.cpp

CTest can't forward command line arguments to the test runner, so add the option to using an environment variable to enable features instead.
CMake issue tracking the feature that would have been needed:
https://gitlab.kitware.com/cmake/cmake/-/issues/20470
Tests which aren't passing yet have been disabled in CI.

Integration tests: Set up CI testing for TypeGraph

---

.circleci/config.yml

CI tests are experiencing spurious SIGPIPEs with increasing regularity, particularly with running even more tests under type graph. Turn the `--repeat until-pass` flag back up to 2 to allow one retry per test in lieu of fixing this properly. Relates to #189.
CI

ci: retry tests once on failure

---

types/folly_iobuf_type.toml

Required for CodeGen v2, which does not add "using namespace xxx" and uses fully qualified names instead.

Add missing namespace to folly::IOBuf container TOML

---

test/integration/CMakeLists.txt
test/integration/README.md

Currently integration test configs have to be specified manually in the `CMakeLists.txt` file. This changes to using a CMake `GLOB_RECURSE` with the flag [`CONFIGURE_DEPENDS`](https://cmake.org/cmake/help/latest/command/file.html#glob-recurse) (available since 3.12) which causes the build to check the glob each time and re-configure CMake if it has changed.
```
$ cp test/integration/std_string{,_2}.toml && make test
[0/2] Re-checking globbed directories...
-- GLOB mismatch!
[1/2] Re-running CMake...
...
```
Otherwise:
```
$ make test
[0/2] Re-checking globbed directories...
[0/11] Building drgn
...
```

integration: add GLOB with CONFIGURE_DEPENDS to pick up toml files

---

oi/CodeGen.cpp
oi/CodeGen.h

Codegen failed (non-deterministically) to produce container implementations if it ran twice, which it does under multi-argument probing. This change adds the `usedContainers_` list as a class field, meaning it has the same lifetime as the vector and thus the pointers should be consistent, and each new codegen gets to add its own containers.
It makes a few of the `namespace {}` functions a little messy, but I did it this way instead of adding them as member functions to prevent exposing the private interface of `Codegen.h` to the type_graph internal `Container`.
- CI

codegen: store prev defined containers as a class field

---

oi/Features.cpp
oi/Features.h
oi/OID.cpp
tools/OITB.cpp

Features previously had no descriptions and were all crammed onto one line. Improve the help of OID and OITB to make it clearer what each feature does.
This isn't ideal formatting but it's definitely better than what was there before. I might clean this up more at some point.
Before:
```
$ make oid && build/oid --help
usage: oid ...
-h,--help                      Print this message and exit
-p,--pid <pid>                 Target process to attach to
-c,--config-file               </path/to/oid.toml>
-x,--data-buf-size <bytes>     Size of data segment (default:1MB)
Accepts multiplicative suffix: K, M, G, T, P, E
-d,--debug-level <level>       Verbose level for logging
-r,--remove-mappings           Remove oid mappings from target process
-s,--script                    </path/to/script.oid> …
```

help: improve feature descriptions

---

oi/CodeGen.cpp
oi/Features.cpp
oi/Features.h
oi/FuncGen.cpp
oi/FuncGen.h
oi/OICodeGen.cpp
oi/OIDebugger.cpp
oi/OIDebugger.h
oi/TreeBuilder.cpp

Adds a timing call at the beginning and end of the generated code functions and store the time taken in nanoseconds in the data segment. Currently this is output at `LOG(INFO)` level. IMO this belongs in RocksDB and `oid_out.json`, but it requires a bit of a format change so I'll leave it until it's necessary.
This required adding another `uintptr_t` typed element to the data segment prefix, because adding it at the end of the data segment means keeping overhead of setting lengths and such after the call. Probe effect should be minimal as is, but as it's feature gated and off by default I haven't bothered measuring it. I added some names to pieces in these entry functions while I was in there, and also cleaned up a type in the typed data segment entry.
- CI
- `[]: make test: 100% tests …

Timing: add generated code jit timing feature

---

test/test_add_padding.cpp
test/test_alignment_calc.cpp
test/test_flattener.cpp
test/test_name_gen.cpp
test/test_remove_top_level_pointer.cpp
test/test_topo_sorter.cpp

This was a purely mechanical change made with some find-and-replace macros. The tests still pass afterwards.
The second commit I'm bundling into this PR is a lot smaller and just moves the last remaining tests onto using the type_graph_utils helpers.

Unit tests: Remove unnecessary make_unique calls

---

oi/CodeGen.cpp
oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
test/test_topo_sorter.cpp
test/type_graph_utils.cpp
test/type_graph_utils.h

For std::vector and std::list, template parameters are not required to be defined before they can be used. Delay sorting them until the end.
Also fix a CodeGen bug where we were defining typedefs in the middle of the forward declarations. They only need to be defined when other types are defined.
References:
https://eel.is/c++draft/vector.overview#4
http://eel.is/c++draft/list.overview#3
https://eel.is/c++draft/forward.list.overview#4

TopoSorter: Fix sorting of container template parameters

---

oi/CodeGen.cpp
oi/type_graph/AddPadding.cpp
oi/type_graph/AddPadding.h
oi/type_graph/DrgnParser.cpp
oi/type_graph/Flattener.cpp
oi/type_graph/Printer.cpp
oi/type_graph/RemoveIgnored.cpp
oi/type_graph/Types.h
test/integration/bitfields.toml
test/test_add_padding.cpp
test/test_alignment_calc.cpp
test/test_drgn_parser.cpp
test/test_flattener.cpp
test/test_remove_ignored.cpp

- Change member and parent offsets to work in bits, not bytes
- Printer still displays offsets in bytes, with decimals when usingbitfields
- AddPadding: Don't pad bitfields
- CodeGen: Emit code for bitfields

TypeGraph: Support bitfields

---

dev.oid.toml
oi/CodeGen.cpp
oi/CodeGen.h
oi/OICache.h
oi/OICodeGen.cpp
oi/OICodeGen.h
oi/OID.cpp
oi/OIDebugger.cpp
oi/OIDebugger.h
oi/OIUtils.cpp
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/TypeIdentifier.h
test/ci.oid.toml
test/test_type_identifier.cpp
tools/combine_configs.py

As we now store ContainerInfo objects in OICodeGen::Config, we can not copy it any more. Change all places that took copies to take const references instead.
The copy in OICodeGen modified membersToStub, the contents of which form part of OICache's hash. However, as OICache also previously had its own copy, it would not have been OICodeGen's modifications.

Take list of pass-through types from config instead of hardcoding

---

oi/type_graph/CMakeLists.txt
oi/type_graph/DrgnParser.cpp
oi/type_graph/Printer.cpp
oi/type_graph/TypeGraph.cpp
oi/type_graph/TypeGraph.h

Should save some memory and improve performance by not having loads of copies of primitive types.

TypeGraph: Make Primitive types singletons

---

.circleci/config.yml
oi/CodeGen.cpp
oi/CodeGen.h
types/thrift_isset_type.toml

Adds Thrift Isset support with `-ftyped-data-segment`. This was a little fiddly as a few of the CodeGen functions rely on knowing if they're the last run of the loop, which falls apart when ignoring padding. The final generated code is quite neat though.
- `OID_TEST_ARGS='-ftyped-data-segment' make test: 96% tests passed, 24 tests failed out of 591` (thrift failures gone)
- CI
Generated code example:
```
template <typename DB>
class TypeHandler<DB, MyThriftStructUnpacked_0> {
using thrift_data = apache::thrift::TStructDataStorage<cpp2::MyThriftStructUnpacked>;
static int getThriftIsset(const MyThriftStructUnpacked_0& t, size_t i) {
if (&thrift_data::isset_indexes == nullptr) return -1;
auto idx = thrift_data::isset_indexes[i];
if (idx == -1) return -1;
return t.__isset_3.get(idx);
} …
```

thrift isset: add type handler

---

.circleci/config.yml
types/seq_type.toml

Fixes vector handler for custom allocators.
- CI

typed data segment: fix vector handler for custom allocators

---

oi/type_graph/AddPadding.cpp
oi/type_graph/DrgnParser.cpp
oi/type_graph/DrgnParser.h
oi/type_graph/RemoveIgnored.cpp
oi/type_graph/TypeGraph.cpp
oi/type_graph/TypeGraph.h
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/Types.h
test/test_add_padding.cpp
test/test_alignment_calc.cpp
test/test_codegen.cpp
test/test_flattener.cpp
test/test_name_gen.cpp
test/test_remove_ignored.cpp
test/test_remove_top_level_pointer.cpp
test/test_topo_sorter.cpp
test/test_type_identifier.cpp
test/type_graph_utils.cpp
test/type_graph_utils.h

These aren't used for anything yet, but should be useful for stable IDs when printing nodes before and after passes and for faster cycle detection than the current map of pointers.

TypeGraph: Add Node IDs to non-leaf types

---

oi/CodeGen.cpp
oi/CodeGen.h
oi/type_graph/AddChildren.cpp
oi/type_graph/AddPadding.cpp
oi/type_graph/AlignmentCalc.cpp
oi/type_graph/DrgnParser.cpp
oi/type_graph/DrgnParser.h
oi/type_graph/Flattener.cpp
oi/type_graph/NameGen.cpp
oi/type_graph/Printer.cpp
oi/type_graph/RemoveIgnored.cpp
oi/type_graph/RemoveTopLevelPointer.cpp
oi/type_graph/TopoSorter.cpp
oi/type_graph/TypeGraph.cpp
oi/type_graph/TypeGraph.h
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/Types.h
oi/type_graph/Visitor.h
test/test_add_padding.cpp
test/test_alignment_calc.cpp
test/test_codegen.cpp
test/test_drgn_parser.cpp
test/test_flattener.cpp
test/test_name_gen.cpp
test/test_remove_ignored.cpp
test/test_remove_top_level_pointer.cpp
test/test_topo_sorter.cpp
test/test_type_identifier.cpp

References must always have a value, so are semantically clearer than pointers for variables which must always be set.
No functional changes.

TypeGraph: Switch from pointers to references

---

oi/CodeGen.cpp
oi/Features.cpp
oi/Features.h
oi/type_graph/AddPadding.cpp
oi/type_graph/AddPadding.h
oi/type_graph/Flattener.cpp
oi/type_graph/Flattener.h
test/test_add_padding.cpp
test/test_flattener.cpp

This will eventually be used to enable running with Tree Builder v2.
For now, when it is disabled it puts CodeGen v2 into compatibility mode, disabling features which weren't present in CodeGen v1 so that its output can be understood by Tree Builder v1.

TypeGraph: Add "--tree-builder-v2" flag

---

oi/type_graph/TypeIdentifier.cpp
test/test_type_identifier.cpp

Pass-through-types represent classes to be turned into containers. We don't want these to turn these containers into Dummy's on a second run of TypeIdentifier.

TypeIdentifier: Preserve container types

---

oi/type_graph/AddChildren.cpp
oi/type_graph/AddChildren.h
oi/type_graph/AddPadding.cpp
oi/type_graph/AddPadding.h
oi/type_graph/AlignmentCalc.cpp
oi/type_graph/AlignmentCalc.h
oi/type_graph/Flattener.cpp
oi/type_graph/Flattener.h
oi/type_graph/NameGen.cpp
oi/type_graph/NameGen.h
oi/type_graph/RemoveIgnored.cpp
oi/type_graph/RemoveIgnored.h
oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/TypeIdentifier.h
oi/type_graph/Visitor.h

`visit(Type&)` and `visit(Type*)` were helper functions than did cycle detection and provided nicer syntax for the `type.accept(*this)` calls.
However, because they overloaded the `visit()` function, it was easy to accidentally call a concrete visit method (e.g. `visit(Class&)`) instead of the virtual-dispatching `visit(Type&)`.
By changing the name of this wrapper, it will make it much more obvious when code is introduced which bypasses the cycle detection.

TypeGraph: Rename visit(Type) functions to accept(Type)

---

oi/type_graph/NameGen.cpp
test/test_name_gen.cpp

GCC includes dots in vptr member names, e.g. "_vptr.MyClass". These aren't valid in C++, so we must replace them.

NameGen: Remove invalid characters from member names

---

oi/type_graph/Flattener.cpp
test/test_flattener.cpp
test/type_graph_utils.cpp
test/type_graph_utils.h

Also add negative tests for fixAllocatorParams(), covering this case and more.

Flattener: Fix seg-fault in the case of specific bad DWARF

---

oi/type_graph/AddChildren.cpp
oi/type_graph/AddChildren.h
oi/type_graph/Flattener.cpp
oi/type_graph/Types.cpp
oi/type_graph/Types.h
test/CMakeLists.txt
test/test_add_children.cpp
test/test_drgn_parser.cpp
test/test_drgn_parser.h

Use fully qualified names to determine if a class is really the child of our type. It may be that it is the child of another type with an identical name in another namespace.

AddChildren: Filter out false children

---

oi/OICodeGen.cpp

Summary:
If a container has 0 template params (e.g. IOBuf, IOBufQueue), it wasn't being added to containerTypeMap. This causes the deserialization to go wrong as TreeBuilder doesn't treat the types as container
Test Plan:
make test

Add container without template params to container map

---

oi/OICodeGen.cpp
test/integration/std_tuple.toml

Summary:
Stubbing tuple without alignment info can cause failures. I added a test case for this which failed before this fix but works now.
Test Plan:
Ran the test.

Stop stubbing tuple

---

oi/type_graph/Flattener.cpp
oi/type_graph/Flattener.h
oi/type_graph/NodeTracker.h
oi/type_graph/TypeGraph.cpp
oi/type_graph/TypeGraph.h
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/TypeIdentifier.h
oi/type_graph/Types.h
oi/type_graph/Visitor.h
test/CMakeLists.txt
test/test_node_tracker.cpp

Added to Flattener and TypeIdentifier passes for now as a proof-of-concept. Other passes can come later.

TypeGraph: Introduce NodeTracker for efficient cycle detection

---

.circleci/config.yml
oi/type_graph/RemoveIgnored.cpp
test/test_remove_ignored.cpp

This means they will be treated as padding, so CodeGen will not try to store any data for them.

RemoveIgnored: Set names for removed members to AddPadding::MemberPrefix

---

.circleci/config.yml
CMakeLists.txt
include/oi/types/dy.h
include/oi/types/st.h
oi/CodeGen.cpp
oi/Features.cpp
oi/Features.h
oi/FuncGen.cpp
oi/FuncGen.h
oi/Headers.h
oi/OICompiler.cpp
oi/OIUtils.cpp
oi/exporters/TypeCheckingWalker.cpp
oi/exporters/TypeCheckingWalker.h
oi/exporters/test/TypeCheckingWalkerTest.cpp
oi/types/test/StaticTest.cpp
resources/CMakeLists.txt
test/CMakeLists.txt
test/integration/arrays.toml

- Adds a system to convert the static types from #157 into a dynamic representation, using constexpr and all computed at compile time.
- Tests that the dynamic representation is accurate for the various static types.
- Adds a `TypeCheckingWalker` which allows you to extract from a data segment with type knowledge. For example, the number of items in a list (N) must be succeeded by N*Elements of the list.
- Tests `TypeCheckingWalker` against each existing dynamic type.
It does not stitch these parts together for use in TreeBuilder yet. That will be in the next PR and will finish off phase 2.
Relates to #95 
- CI

TreeBuilder Type Checking part 2A

---

oi/type_graph/TypeGraph.h
oi/type_graph/Types.h

The check for whether to require a node ID is completed in two places, neither of which are at the type which describes whether it needs a node ID. Move this boolean to within the types for clarity/deduplication.
- CI

type_graph: deduplicate has_node_id

---

oi/CodeGen.cpp

Padding only structs generate bad code because of a missing semi colon. Fix that.
- CI

typing: handle padding only structs

---

oi/CodeGen.cpp

I reordered the RemoveTopLevelPointer pass to match the scheme, but there should be no functional changes.

CodeGen: Add comments explaining the order of passes

---

oi/OIDebugger.cpp
oi/OIDebugger.h

The `OIDebugger` class provides a public interface for oid to detach or continue the main target thread via `PTRACE_DETACH` and `PTRACE_CONT` requests respectively. The `OIDebugger` implementation has a number of call sites which continue a thread but it may not be the main thread (`traceePid`) and we may need to pass a signal to inject via the `data` parameter. This change simply tidies all these individual call sites under a common private implementation. The public interface has been converted to use the use the private interface for its close requests.
There are a few PTRACE_DETACH request sites in `OIDebugger.cpp` and I'll tify them up into a common interface in another change.
A `make test` has no new failures.

provide common interfaces for continue and detach requests

---

CMakeLists.txt
test/CMakeLists.txt
test/integration/CMakeLists.txt

The internal version of GoogleTest we were using has disappeared and the CentOS version is old. Vendor it with FetchContent.
- CI
- `make clobber; make configure-devel && make test`
- `make clobber; make configure-static && make test`
Static is a complete mess, and there are a tonne of test failures on it too. I think this is pre-existing though?

googletest: change to FetchContent

---

test/integration/cycles.toml

OID hides the initial raw pointer in the `cycles.raw_ptr` test. Add a second test which wraps this pointer so OID sees the entirety of the cycle.
- CI

test: cycles: add test where oid sees the initial raw pointer

---

oi/type_graph/AddPadding.cpp
test/test_add_padding.cpp

The underlying type of bitfield is important to the size of a struct:
```
struct Foo { int64_t bitfield : 1; };
struct Bar { int8_t bitfield : 1; };
sizeof(Foo) = 8;
sizeof(Bar) = 1;
```

AddPadding: Always pad bitfields with "int8_t"s

---

oi/CodeGen.cpp
oi/OITraceCode.cpp

Size static asserts currently tell you the type and the expected size in the log. This is a bit limited as the only bit of invisible information there is the actual size. Layer the static assert behind a struct so the error message is more descriptive.
Annoyingly this does make the message more verbose (3 "lines" of errors rather than 1). I think we can get it back down to 1 if a macro is used to construct a custom static assert message, but this way seemed more C++ friendly.
- CI
New example:
```
/tmp/oid-cache/981275032686841092.cc:154:5: error: static_assert failed due to requirement '24UL == 32UL'
static_assert(ExpectedSize == ActualSize);
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/oid-cache/981275032686841092.cc:159:5: note: in instantiation of template class …
```

Increase verbosity of size static asserts

---

oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
test/test_topo_sorter.cpp

Also rename visitAfter() to acceptAfter() to match the previous renaming of visit() to accept().

TopoSorter: Sort Typedefs before pointers

---

oi/TreeBuilder.cpp
test/integration/folly_shims.cpp
test/integration/folly_small_vector.toml
test/integration/folly_sorted_vector_map.toml
types/map_seq_type.toml
types/small_vec_type.toml

folly::sorted_vector_map's results are not completely accurate, but at least CodeGen v2 matches CodeGen v1 for it now.

Types: Fix folly::small_vector and folly::sorted_vector_map

---

oi/CodeGen.cpp
oi/type_graph/CMakeLists.txt
oi/type_graph/RemoveMembers.cpp
oi/type_graph/RemoveMembers.h
test/CMakeLists.txt
test/test_codegen.cpp
test/test_remove_members.cpp

Also reshuffle CodeGen's passes to fix an alignment bug with removed members.
Change RemoveMembers to actually remove members instead of replacing them with padding. AddPadding must be run afterwards to fill in the gaps.

Rename RemoveIgnored -> RemoveMembers

---

oi/type_graph/DrgnParser.cpp
test/test_add_children.cpp
test/test_drgn_parser.cpp

This makes CodeGen v2 behave the same as CodeGen v1, and there doesn't seem much point in following function pointers either.

DrgnParser: Always stub function pointers

---

oi/CodeGen.cpp
oi/Features.cpp
oi/Features.h
oi/OID.cpp
oi/OIGenerator.cpp
oi/OILibraryImpl.cpp
oi/type_graph/CMakeLists.txt
oi/type_graph/Prune.cpp
oi/type_graph/Prune.h
test/CMakeLists.txt
test/test_prune.cpp

This lets us remove fields from types when they are no longer needed, speeding up later passes.
A secondary benefit of pruning unused types means that we sometimes remove types for which we can't generate correct C++ code. This can allow us to CodeGen for complex types which reference these broken types without actually requiring them (e.g. as template parameters).
Add a new feature flag "prune-type-graph" to control this pass. It makes sense to prune most of the time, but for testing CodeGen functionality on a wider range of types, it will be useful to have the option to not prune.
At the same time I removed the "type_graph::" prefix from a lot of places in CodeGen, as the extra line wrapping the long names caused were making the `CodeGen::transform()` function quite hard to read. The …

TypeGraph: Add Prune pass

---

oi/type_graph/Types.h

This is a quick hack to fix some internal profiling. See comment for details.

TypeGraph: Set alignment for Thrift isset container to 1

---

oi/CodeGen.cpp
oi/type_graph/NameGen.cpp
oi/type_graph/TopoSorter.cpp
test/test_codegen.cpp
test/test_name_gen.cpp

These minor fixes bring CodeGen v2 to parity with CodeGen v1 on the AdFilterData type.
i.e. It now just fails with a small number of static asserts
See commit messages and comments for details on the changes.

CodeGen Fixes

---

oi/type_graph/AlignmentCalc.cpp
test/test_alignment_calc.cpp

We previously only marked as packed if there was no tail padding, which was not a sufficient condition.
The new AlignmentCalcTest.PackedMembers test case is an example which would previously not have been marked as packed.

AlignmentCalc: Mark as packed if members are not aligned

---

tools/OIRP.cpp

Meta policies require that this appears at the top of every source file.

OIRP: Add copyright header

---

oi/type_graph/NameGen.cpp
oi/type_graph/NameGen.h
oi/type_graph/Types.cpp
oi/type_graph/Types.h

Names which were generated on-demand are now stored in member variables, which are set during the ctor and can be regenerated when required (by NameGen).

TypeGraph: Change Type::name() to return a reference instead of a copy

---

oi/type_graph/PassManager.cpp
oi/type_graph/Printer.cpp
oi/type_graph/Printer.h
oi/type_graph/TypeGraph.cpp
oi/type_graph/TypeGraph.h
test/test_add_children.cpp
test/test_codegen.cpp
test/test_drgn_parser.cpp
test/test_flattener.cpp
test/test_remove_top_level_pointer.cpp
test/test_type_identifier.cpp
test/type_graph_utils.cpp
test/type_graph_utils.h

This removes Printer's legacy behaviour of generating an ID for each node as it gets printed. This old method meant that if new nodes were added to or removed from a graph, every ID after the new/removed node would change.
Now IDs are stable so it is easier to follow specific nodes through multiple transformation passes in CodeGen.

Printer: Use NodeIds for stable IDs when printing graphs

---

types/try_type.toml

This is a dirty workaround for the issue raised in #289.
I was able to build and run the probe that was hitting this issue in our internal service.

Workaround for #289 missing symbol

---

oi/type_graph/DrgnParser.cpp
oi/type_graph/Flattener.cpp
oi/type_graph/NameGen.cpp
oi/type_graph/Printer.cpp
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/Types.h
test/TypeGraphParser.cpp
test/test_drgn_parser.cpp
test/test_flattener.cpp
test/test_name_gen.cpp
test/test_prune.cpp
test/test_topo_sorter.cpp

In order to generate the boring bits of a `TypeHandler` class we require the type of value template parameters. For example, we must generate this for an array:
```
template <typename DB, typename T0, uint64_t N0>
struct TypeHandler<DB, std::array<T0, N0>> { ... }
```
Which requires the type of N0.
- CI

DrgnParser: store type of template param value

---

oi/CodeGen.cpp
oi/type_graph/DrgnParser.cpp
oi/type_graph/DrgnParser.h
oi/type_graph/Printer.cpp
oi/type_graph/Printer.h
oi/type_graph/Types.h
test/integration/enums.toml
test/test_add_children.cpp
test/test_drgn_parser.cpp
test/test_drgn_parser.h

It's not enabled yet, but should be useful for the key capture work.

TypeGraph: Add option to record enumerator names

---

oi/type_graph/AddPadding.cpp
oi/type_graph/NameGen.cpp
oi/type_graph/Printer.cpp
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/Types.h
test/TypeGraphParser.cpp
test/test_codegen.cpp
test/test_name_gen.cpp
test/test_type_identifier.cpp

Type Graph deduplicates and modifies names to better fit the generated code, for example `int32_t[4]` becomes `OIArray<int32_t, 4>` and `struct MyStruct` might become `struct MyStruct_0`.
Add an `inputName` which better represents the original input code which can be used when building the tree.
Updated `test_codegen.cpp` and `test_name_gen.cpp` to respect these changes. This is more to assert any changes are deliberate rather than to claim the current ones are correct...
- CI

type_graph: provide inputName for all types

---

types/try_type.toml

TreeBuilder expect 2 values for the `folly::Try<…>` container, but our container code only generated one.

Fix JIT CodeGen for Try<…>

---

test/integration/std_set_custom_comparator.toml
types/set_type.toml

Container V2 implementation for std::set. This closes #306.
```
$ build/test/integration/integration_test_runner --gtest_filter='OilIntegration.std_set_custom_comparator_a' --verbose --preserve
```

std::set implementation for Container V2

---

oi/CodeGen.cpp
oi/OILibraryImpl.cpp

OIL JIT doesn't output verbose information from CodeGen V2. Add the same `SetVLOGLevel` line to `OILibraryImpl.cpp` as in `OID.cpp` to correctly set the output level.
- CI

oil: fix verbosity level in jit oil

---

test/integration/std_map_custom_comparator.toml
types/set_type.toml
types/std_map_type.toml

Implement Container V2 for std::map and update std::set container with `static constexpr element_size`.
Closes issue #π (#314).
```
build/test/integration/integration_test_runner --gtest_filter='OilIntegration.std_map_custom_comparator_a' --verbose```

Implement Container V2 for std::map

---

oi/CodeGen.cpp
oi/OITraceCode.cpp
oi/type_graph/Printer.cpp
oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/TypeIdentifier.h
oi/type_graph/Types.h
test/TypeGraphParser.cpp
test/test_codegen.cpp
test/test_name_gen.cpp
test/test_topo_sorter.cpp
test/test_type_identifier.cpp
types/array_type.toml
types/map_seq_type.toml
types/multi_map_type.toml
types/multi_set_type.toml
types/pair_type.toml
types/seq_type.toml
types/set_type.toml
types/std_map_type.toml

Types within containers were previously named TODO. This sorts it out so they're named as their most resolved type. The current implementation skips Typedef names.
- CI

name contained types properly in treebuilder v2

---

oi/CodeGen.cpp
types/array_type.toml
types/map_seq_type.toml
types/multi_map_type.toml
types/multi_set_type.toml
types/pair_type.toml
types/seq_type.toml
types/set_type.toml
types/std_map_type.toml

Creating `inst::Field`s is mostly repetitive. Deduplicate it in containers with a `make_field` helper. Once exclusive size is fully sorted this can be done for struct members too.
- CI

tbv2: add make_field helper

---

dev.oid.toml
oi/ContainerTypeEnum.h
oi/TreeBuilder.cpp
test/ci.oid.toml
test/integration/std_unordered_map_custom_operator.toml
test/integration/std_unordered_multimap_custom_operator.toml
test/integration/std_unordered_multiset_custom_operator.toml
test/integration/std_unordered_set_custom_operator.toml
types/std_unordered_map_type.toml
types/std_unordered_multimap_type.toml
types/unordered_multiset_type.toml
types/unordered_set_type.toml

Implement Container V2 for each `unordered` containers.
The size overhead was measured using: https://godbolt.org/z/b4qrr3YdM
Closes #302 and #303.
```
$ build/test/integration/integration_test_runner --gtest_filter='OilIntegration.std_unordered_set_custom_operator_a' --verbose
```

Implement Container V2 for `unordered` containers

---

oi/exporters/ParsedData.cpp

Fix double parseVarint for ParsedData::Sum

Fix double parseVarint for ParsedData::Sum

---

website/.gitignore
website/docusaurus.config.js
website/src/pages/index.js

Hello, hope everyone is doing well! :)
I noticed that the website has some default text in the social media preview. I went ahead and tweaked it to not be the default anymore.
In addition, it seems like the favicon dosen't seem to work: https://realfavicongenerator.net/favicon_checker?protocol=https&site=facebookexperimental.github.io%2Fobject-introspection%2F
I attempted to fix this by making the link relative.
Serve website via docusaurus instructions and verify title/meta tag is updated. Also verify that favicon shows up. 
To "test" favicon in production, I removed the leading `/` from the favicon on the live site using inspect element, after which I could see the favicon again. I'll try to follow up to make sure things are working properly on the site for this one.

Tweak social media previews for Oid website

---

dev.oid.toml
test/ci.oid.toml
test/integration/folly_f14_fast_set.toml
test/integration/folly_f14_node_set.toml
test/integration/folly_f14_value_map.toml
test/integration/folly_f14_value_set.toml
test/integration/folly_f14_vector_set.toml
types/f14_fast_set.toml
types/f14_node_set.toml
types/f14_value_map.toml
types/f14_value_set.toml
types/f14_vector_set.toml

Implement Container V2 for `folly::F14ValueSet`, `folly::F14VectorSet`, `folly::F14NodeSet`, and `folly::F14FastSet`. I've also sneaked in an implementation for `folly::F14ValueMap`, which was still missing.
Note that these implementation don't report byte-accurate footprint for the containers. They will need to be revisited to implement proper accounting.
`make test`

Implement Container V2 for F14Set

---

oi/exporters/Json.cpp

Summary: The iterator was incremented without checking it in the JSON exporter. This caused an assertion to trigger on the last run in debug mode (weirdly no crashes). This change should fix that by checking the iterator at the increment site and not just when the loop rolls around.
Differential Revision: D49151482

json: fix bug where a past the end iterator would be dereferenced

---

include/oi/IntrospectionResult-inl.h
include/oi/IntrospectionResult.h

IntrospectionResult did not support range based for loops (`for (const auto& el : result) { ... }`) because it was missing a `begin()` and `end()` implementation. Add these, forwarding to the `cbegin()` and `cend()` implementations because this iterator is always constant.
- CI
- https://www.internalfb.com/diff/D49234918

oil: update iterator for range based for loops

---

include/oi/exporters/inst.h
oi/CodeGen.cpp
oi/FuncGen.cpp
oi/IntrospectionResult.cpp
types/array_type.toml
types/f14_fast_map.toml
types/f14_fast_set.toml
types/f14_node_map.toml
types/f14_node_set.toml
types/f14_value_map.toml
types/f14_value_set.toml
types/f14_vector_map.toml
types/f14_vector_set.toml
types/map_seq_type.toml
types/multi_map_type.toml
types/multi_set_type.toml
types/optional_type.toml
types/pair_type.toml
types/seq_type.toml
types/set_type.toml
types/shrd_ptr_type.toml
types/small_vec_type.toml
types/std_map_type.toml
types/std_unordered_map_type.toml
types/std_unordered_multimap_type.toml
types/uniq_ptr_type.toml
types/unordered_multiset_type.toml
types/unordered_set_type.toml

Summary: Previously on large types OIL would have problems with corrupting the `std::stack<exporter::inst::Inst>` that is passed to the processors. This change hides the implementation of the stack from the processors by wrapping the call to emplace in a `std::function` written by the non-generated code, which solves the test case I've seen for this crashing. It also allows us to easily change the stack implementation in future - I plan to change it to a `std::stack<T, std::vector<T>>` in a follow up.
Reviewed By: tyroguru
Differential Revision: D49273116

oil: change std::stack reference to a std::function

---

include/oi/types/st.h
oi/CodeGen.cpp

The generated code for traversing a class uses almost entirely the delegate form on the static type. However, for the last element, it drops the form as `delegate()` doesn't have the right behaviour. If left with a Pair or Sum delegate would behave incorrectly for the last element.
Add a new `consume()` function to the static types that works in the same way as delegate but always returns a `Unit`. This allows changing the class traversal function to be entirely fluent, neatening it up.
- CI
Before:
```cpp
static types::st::Unit<DB> getSizeType(
const SimpleStruct_0& t,
typename TypeHandler<DB, SimpleStruct_0>::type returnArg) {
auto ret = returnArg
.delegate([&t](auto ret) { return OIInternal::getSizeType<DB>(t.a_0, ret); })
.delegate([&t](auto ret) { return …
```

static types: add consume function similar to delegate

---

tools/OILGen.cpp

Current output of OILGen is always without debug. This hides things like the printed type graph from the end user, which would be useful in the logs of a build failure. Also rename the `-d` flag which was for jumping JIT code to `-j`, as `-d` is used in all the other tools for debug output level.
- CI
- Tested internally with the BUCK integration in [D49369823](https://www.internalfb.com/diff/D49369823)

oilgen: add debug flag

---

oi/OIGenerator.cpp

OIGenerator appends linkage (symbol) names to paths. With particularly long symbols, this throws because the filesystem won't accept a filename that long. Hash them so the length is consistent.
This will go away eventually when I change OILGen to support multiple entrypoints in a single object file. This hasn't happened yet though, so this is a stop gap.
Tested it internally. Errors early on a big symbol beforehand, gets to codegen properly afterwards.

oilgen: hash linkage names in output path

---

oi/type_graph/DrgnParser.h
test/test_drgn_parser.cpp
test/test_drgn_parser.h

We only want to do the extra work if it's explicitly requested.
chaseRawPointers is already explicitly requested whenever it's needed and readEnumValues currently isn't needed at all.

DrgnParser: Options should default to false

---

oi/OIGenerator.cpp

oilgen currently attempts to demangle all symbols it gets from drgn, even if they're empty. If the symbol is empty this causes ASAN to fail in some libiberty (I think) function. Check first if the symbol is empty and skip it which solves the ASAN problems.
- CI
- Tested with [D49413028](https://www.internalfb.com/diff/D49413028)

oilgen: avoid demangling empty symbols

---

tools/OILGen.cpp

Although #348 built fine internally and on the CI, it fails on my devserver. Add the `gflags.h` header to satisfy a missing symbol.
- `make clobber; make configure-devel && make test`

oilgen: add missing gflags header

---

oi/CodeGen.cpp
test/integration/enums.toml
test/test_drgn_parser.cpp

Enum classes were previously generated as their integer type. Generate them as enum classes with that integer type as the base so they can be identified separately in `NameProvider` for OIL.
- CI
Updated the enum tests to check names are generated correctly. Added a new test which generates both the enum and its base type in one codegen CU. This failed to compile previously as it created two different copies of `NameHandler<uint8_t>`.

codegen: generate enums as enum class

---

oi/type_graph/Printer.cpp
oi/type_graph/Printer.h

Dummy and DummyAllocator nodes had been changed to use NodeIds, but were still printed out in full when visited for a second time.
`[[nodiscard]]` prevents future bugs of this type by turning them into compilation errors.
Example of the now-fixed bug:
```
[1]  Container: std::map<int32_t, int32_t, DummySizedOperator<0, 0, 8>, std::allocator<std::pair<int32_t const, int32_t>>>
Param
Primitive: int32_t
Param
Primitive: int32_t
Param
[2]       Dummy [less<int>]
Param
...
[3]   Container: std::map<int32_t, int32_t, DummySizedOperator<0, 0, 8>, std::allocator<std::pair<int32_t const, int32_t>>>
Param
Primitive: int32_t
Param
Primitive: int32_t
Param
[2]
Dummy [less<int>]
Param
...
```
With this patch, the second "Dummy" line will not be printed.

Printer: Make prefix() [[nodiscard]] and fix bug printing Dummy nodes

---

CMakeLists.txt

Update RocksDB to v8.5.3.
Relates to #359  
- CI
- `make clobber; make configure-devel && make test`
(note: these commands aren't external contributor friendly. we should find a way to better present them.)

rocksdb: update to v8.5.3

---

oi/OITraceCode.cpp
oi/type_graph/DrgnParser.cpp
oi/type_graph/TypeGraph.cpp
oi/type_graph/Types.cpp
oi/type_graph/Types.h
test/TypeGraphParser.cpp
test/integration/std_pair.toml
test/test_add_children.cpp
test/test_drgn_parser.cpp

`uintptr_t` is a typedef of `uint64_t` but doesn't appear as such in the type graph. This meant if we generated a `uintptr_t` and also had a `uint64_t` in the output, they would get a `NameProvider<T>` each and this would cause a compilation failure.
Stop generating `uintptr_t` for these cases where we're stubbing pointers (the only cases it gets generated in). Change this to a special enum class called `StubbedPointer` with the same memory footprint. This will make stubbed pointers easier to search for in the output and prevents the type collision of the primitives.
- CI
- `make test`

prevent name collision between uintptr_t and uint64_t

---

oi/CodeGen.cpp
oi/CodeGen.h
oi/type_graph/DrgnParser.cpp
oi/type_graph/DrgnParser.h
test/test_drgn_parser.cpp

Lots of places rely on reference stability of ContainerInfo objects (CodeGen's deduplication, Container nodes' containerInfo_ member).
In the key capture work, we need to be able to append to this list, which would invalidate references before this change.
`std::deque<ContainerInfo>` would also be another option we could go with.

CodeGen: Store list of ContainerInfos in unique_ptrs for reference stability

---

oi/CodeGen.cpp
oi/FuncGen.cpp
oi/FuncGen.h
oi/OICodeGen.cpp

JIT logging was broken in codegen v1 after removing externs from `OITraceCode.cpp`. Move the logic into `FuncGen` so it can be shared between v1 and v2.
- CI
```
$ oid --script-source entry:oid_test_case_simple_struct:arg0 -fjit-logging --pid 2609805
...
$ cat /tmp/*jit*log
SimpleStruct @00007ffeed0a6f00
a @00007ffeed0a6f00
obj @00007ffeed0a6f00
b @00007ffeed0a6f04
obj @00007ffeed0a6f04
c @00007ffeed0a6f08
obj @00007ffeed0a6f08
```
```
$ oid --script-source entry:oid_test_case_simple_struct:arg0 -fjit-logging -ftype-graph --pid 2609805
...
$ cat /tmp/*jit*log
SimpleStruct @00007ffeed0a6f00
a @00007ffeed0a6f00
obj @00007ffeed0a6f00
b @00007ffeed0a6f04
obj @00007ffeed0a6f04
c @00007ffeed0a6f08
obj @00007ffeed0a6f08
```

jit logging: fix for codegen v1

---

test/integration/sorted_vector_set.toml
types/sorted_vec_set_type.toml

folly::sorted_vector_set is a nice simple wrapper over a vector. It forwards the size and capacity of the vector properly, so this is a nice and simple container to support. It has minimal testing already.
- CI

Implement Container V2 for folly::sorted_vector_set

---

include/oi/exporters/CSV.h
oi/CMakeLists.txt
oi/exporters/CSV.cpp

Implement a new CSV exporter for OIL's `IntrospectionResult`.
We don't have a way to test extra exporters right now, but trust me it's working!

Add CSV Exporter

---

CMakeLists.txt
include/oi/oi-jit.h
oi/Config.cpp
oi/Config.h
oi/EnumBitset.h
oi/OID.cpp
oi/OIDebugger.cpp
oi/OIGenerator.cpp
oi/OILibraryImpl.cpp
test/integration/gen_tests.py
test/integration/runner_common.cpp
test/integration/runner_common.h

Previously OID/OIL required exactly one configuration file. This change makes it so you can supply 0 or more configuration files. 0 is useful if you have pre-generated the cache or use some sort of remote generation system. 1 is useful for the common case, where you have a configuration file that describes your entire source and use just that. More are useful if you have supplemental bits of config you wish to apply/override - see the changes to the integration test framework where we do exactly this.
This isn't super well tested. It works for the test cases which add features via the config or enable `codegen.ignore`.
- CI

support 0 to many config files

---

oi/type_graph/DrgnParser.cpp
oi/type_graph/EnforceCompatibility.cpp
oi/type_graph/Flattener.cpp
oi/type_graph/Printer.cpp
oi/type_graph/Printer.h
oi/type_graph/TypeGraph.cpp
oi/type_graph/Types.cpp
oi/type_graph/Types.h
oi/type_graph/Visitor.h
test/TypeGraphParser.cpp
test/test_drgn_parser.cpp
test/test_enforce_compatibility.cpp
test/test_flattener.cpp

Any Incomplete type encountered by the DrgnReader gets effectively turned into a Primitive::Kind::Void. This makes debugging these issues fairly difficult, as we lose all information regarding the Incomplete type.
This PR changes this behaviour, so that we can still identify the type that got classified as Incomplete.
Update the test "DrgnParserTest.PointerIncomplete" to take the new `Incomplete` node into account.
Update the `TypeGraphParser` to rebuild the `Incomplete` node.

Add the `Incomplete` Type node

---

oi/CMakeLists.txt
oi/CodeGen.cpp
oi/ContainerInfo.cpp
oi/ContainerInfo.h
oi/EnumBitset.h
test/integration/thrift_isset.toml
types/README.md
types/thrift_isset_type.toml

Adds the option for required features to container definitions. These cause the container not to be passed to `DrgnParser` if that feature is not enabled during code generation. The thrift isset type does not currently work with `tree-builder-v2` and only provides benefit with `capture-thrift-isset`. This change makes sure the container is ignored if it won't be useful, allowing code generation under `tree-builder-v2`.
- CI

containers: add required features

---

oi/OIGenerator.cpp
oi/OIGenerator.h
tools/OILGen.cpp

Summary: Extend the multiple config files system to OILGen, the piece it was originally designed for. This allows for specifying additional configs which say which keys of maps to capture.
Differential Revision: D50105138

oilgen: accept multiple config files

---

include/oi/IntrospectionResult.h
include/oi/exporters/Json.h
oi/IntrospectionResult.cpp
oi/exporters/Json.cpp
test/integration/capture_keys.toml

Capture keys data can't currently be grouped on easily in queries, as it only appears on the `Element` (corresponding to a DB row) that it directly affects. Include it in the type path from the iterator where present to allow grouping. This can still be easily regexed out in queries (`s/[.*]/[]/`) to get the old behaviour.
The downside of this is every instance in this vector is now a string, that also gets copied for rubbish reasons. This should be changed to either a `string/string_view` data structure that stores efficiently and deallocates only when necessary, or some secondary stack in the iterator that holds the real strings. Most strings will not need allocating, and yet are anyway. Problem for down the line.
- CI

capture_keys: include data in type path

---

oi/CodeGen.cpp
test/integration/std_vector.toml
test/integration/std_vector_del_allocator.toml

Exclusive size of fields in containers was previously incomplete, assuming the exclusive size to be static size. This is incorrect for classes as the exclusive size should be set to the size of the class less the size of each member, in other words the padding of the class.
Add an `ExclusiveSizeProvider` similar to `NameProvider`, which defaults to `sizeof(T)` but allows overriding for types which need it.
Closes #301
- CI
- Added a new test for vector containing struct
- Enabled skipped test

tbv2: fix exclusive size of elements in containers

---

oi/OICache.cpp
oi/OIDebugger.cpp

Summary: More moving code out of the `cea` subdirectory. This is moving the GOBS cache code which is contained in the 'internal' subdirectory. I'm hoping I get some auto generated diffs to push to GitHub for the third party source changes...
Reviewed By: JakeHillion
Differential Revision: D50366591

move cea/object-introspection/internal -> object-introspection/internal

---

CMakeLists.txt
oi/OICache.cpp
oi/OID.cpp
oi/OIDebugger.cpp
oi/Portability.h

Summary:
Spin around our open/closed source checks. Previously we defined `OSS_ENABLE` in open source builds. This change defines `OI_META_INTERNAL` instead. This is nicer, as external users don't have to do anything special to get a working build.
Use this new macro to define a boolean constant in a new header `Portability.h`. This is inspired by Folly, and makes the internal build easier - definitions in Buck2 have to propagate up from a dependency instead of down from one. Annoyingly we can't use `if constexpr` for a lot of the previous `#ifdef` blocks as we conditionally include the headers. Longer term we could fix this by exposing a header interface but no source, allowing these to build but not be compiled in. For now I did something weird: I defined a function style macro in …

add portability.h

---

include/oi/oi.h

OIL AoT compilation with `oilgen` currently requires the presence of the `introspect` symbol. If the compiler inlines this symbol then generation fails, which is happening when using the `tryIntrospect` method. Add the `noinline` attribute to solve this.
I tested it, really.

oil: make AoT introspect noinline

---

CMakeLists.txt
oi/OICompiler.cpp
oi/OICompiler.h

`OICompiler.cpp` was stuck on C++17 while the rest of the project is C++20. This is annoying and complicates things, like not being able to use `std::span`s in this single file. Remove this restriction as LLVM15 doesn't have any problems with it, and replace the `std::string_view<uint8_t>` with a proper `std::span<uint8_t>`.
- CI
- `make test`
Disassembly LGTM:
```
$ stest OidIntegration.simple_struct
...
Disassembled Code
I1024 07:37:05.675088 847381 OICompiler.cpp:460] 7f9222a00080:  push    r14
I1024 07:37:05.675093 847381 OICompiler.cpp:460] 7f9222a00082:  push    rbx
I1024 07:37:05.675096 847381 OICompiler.cpp:460] 7f9222a00083:  push    rax
I1024 07:37:05.675101 847381 OICompiler.cpp:460] 7f9222a00084:  mov     rbx, rdi
I1024 07:37:05.675109 847381 OICompiler.cpp:460] 7f9222a00087: …
```

compiler: update to c++20

---

include/oi/IntrospectionResult.h

Changes the implementation of the iterator instruction stack from `std::deque` to `std::vector`. This means a few things:
- No reference stability. We don't currently use it and it will stop us accidentally using it.
- Smaller allocations with few elements. `std::deque` allocates a tonne of memory when it contains even a single element, so is inefficient with small sizes.
- Better spatial locality. The contiguous nature of a vector is good for spatial locality, which makes sense here as we use this as a stack.
- CI

tbv2: change instruction stack from deque to vector

---

include/oi/exporters/inst.h
oi/IntrospectionResult.cpp
types/seq_type.toml

Currently a container type has to do many instruction stack pushes depending on the number of fields. This might cause several allocations and wastes a lot of memory. Add a `Repeat` type which stores a field and a number of times it should be repeated. This causes the instruction stack size to grow by O(1) for a very large container instead of O(n).
The downside is this is a double sized instruction and increases the instruction variant from 16 bytes to 24. An alternative would be heap allocating it, but that can be complicated by the JIT boundary and feels slow. Go with this for now and profile it later if necessary.
Converted vector, the simplest sequence type, to have its tests run.
- CI

tbv2: add a repeat instruction

---

oi/type_graph/TopoSorter.cpp
test/test_topo_sorter.cpp

For the containers which are allowed to be declared with incomplete types, it is only the contained types which are allowed to be incomplete. Other template parameters (e.g. allocators) must always be defined before use.

TopoSorter: Only allow certain params to be incomplete

---

oi/type_graph/DrgnParser.cpp

The `drgn` calls sometimes set this cstr to `nullptr`. If this happens the implicit `std::string` constructor in `makeType` throws `std::logic_error`. Explicitly check for `nullptr` after the calls and set `"<incomplete>"` accordingly.
\<redacted\> (I tested it I promise)

incomplete: handle drgn returning a nullptr name

---

oi/CodeGen.cpp
oi/FuncGen.cpp
oi/FuncGen.h
oi/OICodeGen.cpp
oi/OICodeGen.h
oi/OID.cpp

Cleans up some dead code from the OIL v1 -> v2 migration in OICodeGen and FuncGen. OICodeGen doesn't ever generate OIL code now as OIL v2 is exclusively CodeGen v2 and OIL v1 was removed.
- CI
Excited to see the great coverage improvements.

remove oil v1 leftovers

---

test/integration/runner_common.cpp

A change was made a while ago to put the PID at the end of the integration test output line to make it easier to change when running manually. I regressed this when adding multiple config files. Put the PID at the end of the line again.
- `stest OidIntegration.simple_struct` - it's at the end again
- CI

integration: move pid back to end

---

test/test_drgn_parser.cpp
test/test_drgn_parser.h

It now uses '*' as a wildcard character for more powerful matching of type graphs.

DrgnParserTest: Replace testContains with testGlob

---

oi/CodeGen.cpp
oi/CodeGen.h
oi/type_graph/DrgnParser.cpp
oi/type_graph/DrgnParser.h
oi/type_graph/TypeIdentifier.cpp
test/test_add_children.cpp
test/test_codegen.cpp
test/test_drgn_parser.cpp
test/test_drgn_parser.h

Leave it to the new mutator pass IdentifyContainers to replace Class
nodes with Container nodes where appropriate.
This will allow us to run passes over the type graph before identifying
containers, and therefore before we have lost information about the
internal details of the container (e.g. alignment of member variables).

TypeGraph: Stop identifying containers in DrgnParser

---

oi/CodeGen.cpp
oi/OITraceCode.cpp
oi/type_graph/Types.h
test/test_codegen.cpp

Not all containers have 8-byte alignment, so if we want to avoid lots of manual logic for calculating container alignment on a case-by-case basis, we must calculate alignment from the member variables before the Class nodes have been replaced by Container nodes.

TypeGraph: Calculate alignment before identifying containers

---

CMakeLists.txt
oi/OICompiler.h
oi/type_graph/KeyCapture.cpp

add range-v3 library
Adds the range-v3 library which supports features that otherwise wouldn't be
available until C++23 or C++26. I caught a couple of uses that suit it but this
will allow us to use more in future.
Test Plan:
- CI

add range-v3 library

---

.circleci/config.yml
oi/CodeGen.cpp
oi/ContainerInfo.cpp
oi/ContainerInfo.h
oi/Features.cpp
oi/Features.h
oi/FuncGen.cpp
oi/FuncGen.h
oi/OICompiler.cpp
oi/OIGenerator.cpp
oi/OILibraryImpl.cpp
test/integration/arrays.toml
types/README.md

collapse TreeBuilderV2 features
Summary:
Currently there are two features between CodeGen v2 (TypeGraph) and TreeBuilder
v2. These are TypedDataSegment and TreeBuilderTypeChecking. Each of these
features currently has a full set of tests run in the CI and each have specific
exclusions.
Collapse these features into TreeBuilder v2. This allows for significantly
simplified testing as any OIL tests run under TreeBuilder v2 and any OID tests
run under TreeBuilder v1.
The reasoning behind this is I no longer intend to partially roll out this
feature. Full TreeBuilder v2 applies different conditions to containers than
the intermediate states, and writing these only to have them never deployed is
a waste of time.
Test Plan:
- it builds
- CI

collapse TreeBuilderV2 features

---

test/integration/std_list.toml
test/integration/std_list_del_allocator.toml
types/cxx11_list_type.toml
types/list_type.toml

oil: add support for std::list
Summary:
Remove the now useless `handler` and adds the `traversal_func` and `processor`
entries for `std::list`. This type is a bit weird as most of our sequential
containers don't have any overhead on storing the element. I went for the same
approach we take for maps where we have a shared `[]` element covering the map
overhead and below that a `key` & `value`. As we only have a single element
under it which doesn't have a logical name I went for `*`.
Closes #315.
Test Plan:
- CI
- Copied the relevant `std::vector` tests and updated the existing one.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/407).
* #410
* #409
* #408
* __->__ #407

oil: add support for std::list

---

oi/CodeGen.cpp
oi/FuncGen.cpp
types/array_type.toml
types/cxx11_list_type.toml
types/cxx11_string_type.toml
types/f14_fast_map.toml
types/f14_fast_set.toml
types/f14_node_map.toml
types/f14_node_set.toml
types/f14_value_map.toml
types/f14_value_set.toml
types/f14_vector_map.toml
types/f14_vector_set.toml
types/list_type.toml
types/map_seq_type.toml
types/multi_map_type.toml
types/multi_set_type.toml
types/optional_type.toml
types/pair_type.toml
types/seq_type.toml
types/set_type.toml
types/shrd_ptr_type.toml
types/small_vec_type.toml
types/sorted_vec_set_type.toml
types/std_map_type.toml
types/std_unordered_map_type.toml
types/std_unordered_multimap_type.toml
types/uniq_ptr_type.toml
types/unordered_multiset_type.toml
types/unordered_set_type.toml

tbv2: replace DB template param with Ctx
TreeBuilder v2 adds a DB template parameter to every function. This is used as
part of the static type to decide what type of DataBuffer is being used:
currently `BackInserterDataBuffer<std::vector<uint8_t>>` for OIL and it would
be `DataSegmentDataBuffer` for OID.
This change replaces the `DB` template parameter with a more general `Ctx`. Due
to issues with dependent naming it also adds a `using DB` to each `TypeHandler`
which has the same function as before. This allows us to add more "static
context" (typedefs and constants) to functions without changing this signature
again, because changing the signature of everything is a massive pain.
Currently this change achieves nothing because Ctx contains only DB in a static
wrapper. In the next change …

tbv2: replace DB template param with Ctx

---

oi/OIDebugger.cpp

We generally only dump the data segment when there is some issue running tree builder and we want to process it off-host.
Manual testing:
- Confirmed that tree builder is still run by default and that no data segment is dumped
- Confirmed that tree builder is not run and a data segment is dumped when using "-B"

OID: Don't run tree builder if we are dumping the data segment

---

oi/ContainerInfo.cpp
oi/ContainerInfo.h
oi/OICodeGen.cpp

CodeGen v1 and CodeGen v2 must be in sync in order for CodeGen v2 and TreeBuilder v1 to be compatible. This change updates CodeGen v1 to use the same set of containers as CodeGen v2.
This specifically fixes "-ftype-graph -Ftree-builder-v2 -Fcapture-thrift-isset" for Thrift types.
The integration test "thrift_isset_no_capture" covers this, but this bug was missed as the Thrift tests do not run in CI.

OICodeGen: Respect ContainerInfo::requiredFeatures

---

oi/OIDebugger.cpp
oi/OIDebugger.h
oi/Syscall.h

Reverts facebookexperimental/object-introspection#366
We are failing with memfd_create returning EFAULT. This looks to be because the pointer that is passed as the `uname` parameter in the remote syscall is invalid. We see this kind of failure:
```
E1120 10:19:02.390123 99432 OIDebugger.cpp:1717] syscall: Syscall memfd_create failed with error: Bad address
E1120 10:19:02.390393 99432 OIDebugger.cpp:206] Failed to create memory log file
E1120 10:19:02.390416 99432 OIDebugger.cpp:279] setUpLogFile failed!!!
E1120 10:19:02.390434 99432 OID.cpp:397] Failed to initialise segments in target process with PID 99326
```
bpftrace verifies that the memfd_create() is being passed an invalid string.

Revert "jitlog: use a memfd and glog"

---

oi/OIDebugger.cpp
oi/OIDebugger.h
oi/Syscall.h

jitlog: use a memfd and glog
Summary:
Changes jitlog to use a memfd, an anonymous in memory file descriptor, rather
than a file on disk. Also clean up this fd at the end of an OID run rather than
leaving it in the hope it's valid next time.
A previous attempt to land this used a `char*` from the OID process space in
the remote target syscall. Somehow this works with our integration test target,
but not globally. Changed to use the previous behaviour of putting the syscall
arg in the empty text segment. In doing this I noticed that the text segment
wouldn't be initialised at this point on a fresh process, so we were copying
into effectively an uninitialised address. Move the jit log fd setup to after
the segment setup accordingly.
Test plan:
- CI
- Tested on an integration test target as …

jitlog: use a memfd and glog

---

test/integration/thrift_unions.toml

Fix internal build which depends on Thrift.
With a recent Thrift update, we now must also define a destructor for this type.
CI

Integration Tests: Fix thrift_unions tests

---

oi/type_graph/RemoveMembers.cpp
test/test_remove_members.cpp

They must not appear in the final generated code as we'd end up with invalid types with void members, e.g.:
```
struct Foo {
int a;
void myIncompleteMember;
int c;
};
```
Removing them from the type graph early also ensures that padding is calculated correctly.

CodeGen: Remove Incomplete members from Classes

---

oi/OICodeGen.cpp

During AdIndexerUnit tests when  processing a template parameter that is an array we sometimes have no 'name' stored but do have a 'tag'. Use the tag in this case.
Verified on an AdIndexerUnit that failed to codegen with CGV1.

Really, really make sure arrays when used as a template parameter have a name

---

oi/type_graph/IdentifyContainers.cpp
oi/type_graph/IdentifyContainers.h
oi/type_graph/NodeTracker.h
oi/type_graph/Types.cpp
oi/type_graph/Types.h
oi/type_graph/Visitor.h

MutationTracker could only store Type nodes, while ResultTracker is templated on the result type so can store anything.
Template the Visitor base class on the return type of visit() functions.
This sets us up for allowing visitors to return different results from their visit() functions in the future.
This will be used in a future commit introducing DrgnExporter, where we cache drgn_type* results while walking the type graph: #425

Type Graph: Replace MutationTracker with the more general ResultTracker

---

include/oi/IntrospectionResult.h
oi/IntrospectionResult.cpp

capture_keys: store dynamic type path components more efficiently

capture_keys: store dynamic type path components more efficiently

---

oi/CodeGen.cpp
oi/type_graph/AlignmentCalc.cpp
oi/type_graph/AlignmentCalc.h
oi/type_graph/DrgnParser.h
oi/type_graph/Flattener.cpp
oi/type_graph/Flattener.h
oi/type_graph/IdentifyContainers.cpp
oi/type_graph/IdentifyContainers.h
oi/type_graph/Printer.cpp
oi/type_graph/Printer.h
oi/type_graph/Prune.cpp
oi/type_graph/Prune.h
oi/type_graph/TypeIdentifier.cpp
oi/type_graph/Types.h
oi/type_graph/Visitor.h
test/TypeGraphParser.cpp
test/TypeGraphParser.h
test/test_add_children.cpp
test/test_alignment_calc.cpp
test/test_codegen.cpp
test/test_flattener.cpp
test/test_identify_containers.cpp
test/test_prune.cpp
test/test_type_identifier.cpp
test/type_graph_utils.cpp

TypeGraph: Fix handling for classes which inherit from containers
We previously moved container identification later in CodeGen in order
to preserve information for AlignmentCalc.
However, Flattener needs to know if a class is a container in order to
apply its special handling for this case.
This new approach moves container identification in front of Flattener,
but has Container own a type node, representing its layout. This
underlying type node can be used for calculating a container's
alignment in a later pass.

TypeGraph: Fix handling for classes which inherit from containers

---

oi/CodeGen.cpp
oi/CodeGen.h
oi/ContainerInfo.cpp
oi/OIDebugger.cpp
oi/type_graph/CMakeLists.txt
oi/type_graph/DrgnExporter.cpp
oi/type_graph/DrgnExporter.h
oi/type_graph/EnforceCompatibility.cpp
oi/type_graph/Types.cpp
oi/type_graph/Types.h
test/integration/alignment.toml
test/integration/anonymous.toml
test/integration/cycles.toml
test/integration/ignored.toml
test/integration/inheritance_multiple.toml
test/integration/namespaces.toml
test/integration/pointers_incomplete.toml
test/integration/std_conditional.toml
test/integration/std_deque_del_allocator.toml
test/integration/std_list_del_allocator.toml
test/integration/std_priority_queue.toml
test/integration/std_queue.toml
test/integration/std_stack.toml
test/integration/std_variant.toml
test/integration/std_vector_del_allocator.toml
test/integration/templates.toml
test/integration/typedefs.toml
test/test_enforce_compatibility.cpp

Create DrgnExporter to translate Type Graph "Type" nodes into drgn_type structs, suitable for use in OICache and TreeBuilder.

CodeGen v2: Enable independent running without CodeGen v1

---

oi/CodeGen.cpp
oi/CodeGen.h

codegen: remove reliance on drgn type for top level name
Currently we rely on `SymbolService::getTypeName` for getting the hash that's
included in the generated function's name. The value of this must stay the same
to match with the value expected by OIDebugger - changing it causes failure to
relocate when attaching with OID and JIT OIL.
Calculate this name in the `codegenFromDrgn` method and pass it through where
appropriate rather than passing the `drgn_type` itself through.
We don't need to name the type like that when using AoT OIL. Let's
hash the linkage name instead as that is more unique.
Test Plan:
- CI
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/435).
* #421
* …

codegen: remove reliance on drgn type for top level name

---

CMakeLists.txt
oi/CodeGen.cpp
oi/CodeGen.h
oi/OIGenerator.cpp
oi/OIGenerator.h
oi/type_graph/CMakeLists.txt
oi/type_graph/ClangTypeParser.cpp
oi/type_graph/ClangTypeParser.h
oi/type_graph/DrgnExporter.cpp
oi/type_graph/DrgnExporter.h
oi/type_graph/NameGen.cpp
oi/type_graph/NameGen.h
oi/type_graph/Printer.cpp
oi/type_graph/Printer.h
oi/type_graph/RemoveTopLevelPointer.cpp
oi/type_graph/RemoveTopLevelPointer.h
oi/type_graph/Types.h
oi/type_graph/Visitor.h
tools/OILGen.cpp
types/string_type.toml

oilgen: migrate to source parsing
Using debug information generated from partial source (that is, not the final
binary) has been insufficient to generally generate OIL code.
A particular example is pointers to templates:
```cpp
#include <oi/oi.h>
template <typename T>
struct Foo {
T t;
};
template <typename T>
struct Bar {
Foo<T>& f;
};
void foo(const Bar<int>& b) {
oi::introspect(b);
}
```
The pointer/reference to `Foo<int>` appears in DWARF with
`DW_AT_declaration(true)` because it could be specialised before its usage.
However, with OIL, we are creating an implicit usage site in the
`oi::introspect` call that the compiler is unable to see.
This change reworks OILGen to work from a Clang command line rather than debug
information. We setup and run a compiler on the source, giving us …

oilgen: migrate to source parsing

---

types/folly_iobuf_type.toml

tbv2: implement folly::IOBuf
folly::IOBuf does not have TreeBuilder v2 container support. Add it.
The implementation is a direct clone of v1. It still lacks tests.
Test Plan:
- It codegens on a prod type.
- No runtime testing... Bad form, I know.
- Issue created to add integration tests: https://github.com/facebookexperimental/object-introspection/issues/436
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/437).
* #441
* #440
* #439
* #438
* __->__ #437

tbv2: implement folly::IOBuf

---

oi/CodeGen.cpp
types/folly_iobuf_type.toml

tbv2: account for duplicate types when emitting name providers
ClangTypeParser has emitted a duplicate type for `std::allocatr<int8_t>`.
Rather than fixing this, add the same check the compiler will do for the
duplicate templates that `addNames` emits. That is, `template<>
NameProvider<Foo>` will collide if `Foo` is used twice. We can do this by
adding a set of these strings for now. If this shows up regularly it will
likely make sense to deduplicate the type graph with a deduplication pass.
Test plan:
- Fixes the issue in prod. This change is quite logical.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/438).
* #441
* #440
* #439
* __->__ #438
* #437

tbv2: account for duplicate types when emitting name providers

---

oi/CodeGen.cpp
oi/type_graph/ClangTypeParser.cpp
types/folly_iobuf_type.toml

clangparser: provide correct kind for classes/unions
Previously ClangTypeParser assumed all RecordTypes were structs. This is fine
for structs and classes but completely incorrect for unions. Check which type
it is and give type graph the correct one.
Test plan:
- Unions static assert without this change because their size/alignment is
wrong.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/439).
* #441
* #440
* __->__ #439
* #438
* #437

clangparser: provide correct kind for classes/unions

---

oi/CodeGen.cpp
oi/type_graph/ClangTypeParser.cpp
types/folly_iobuf_type.toml

clangparser: provide alignment info for members
Unlike DWARF, the Clang AST is capable of correctly calculating the alignment
for each member. If we do this then AlignmentCalc doesn't traverse into the
member to attempt to calculate the alignment.
This check might be wrong if the field has explicit alignment. That case can be
covered when we have proper integration testing and a repro.
Test plan:
- Without this lots of static asserts occur. With this it's okay.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/440).
* #441
* __->__ #440
* #439
* #438
* #437

clangparser: provide alignment info for members

---

oi/type_graph/ClangTypeParser.cpp

clangparser: mark incomplete arrays as incomplete without failing
Attempting to complete a type which can't be completed currently fails oilgen.
For incomplete arrays, which we know are not possible to complete, return false
deliberately.
`requireCompleteType` likely needs to not fail in all cases in the future. For
now this works.
Test plan:
- `std::unique_ptr<long[]>` used to fail the generation. Now it can
successfully codegen.

clangparser: mark incomplete arrays as incomplete without failing

---

oi/CodeGen.cpp
oi/OITraceCode.cpp
oi/type_graph/DrgnExporter.cpp
oi/type_graph/NameGen.cpp
oi/type_graph/NameGen.h
oi/type_graph/Printer.cpp
oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
oi/type_graph/Types.cpp
oi/type_graph/Types.h
test/TypeGraphParser.cpp
test/integration/pointers_incomplete.toml
test/test_drgn_parser.cpp
test/test_flattener.cpp
test/test_name_gen.cpp
test/test_remove_members.cpp
types/shrd_ptr_type.toml
types/uniq_ptr_type.toml

incomplete: name type in compiler errors
Summary:
We have a good type representation in the Type Graph of an incomplete type and
the underlying type that represents. However, this incomplete type still ends
up in the generated code as `void` which loses information. For example, a
container that can't contain void may fail to compile because it was
initialised with `void` but really its because the type it was supposed to be
initialised with (say, `Foo`) had incomplete debug information.
This change identifies that a type is incomplete in the output by generating it
as an incomplete type `struct Incomplete<struct Foo>`. This allows us to name
the type correctly in the TreeBuilder output and filter for incomplete types,
as well as getting appropriate compiler errors if it mustn't be …

incomplete: name type in compiler errors

---

test/integration/std_optional.toml
types/optional_type.toml

tbv2: fix type names for std::optional
Type names of optional elements were accidentally left as todo. Update
`std::optional` to use `make_field` and correctly name its elements.
Test Plan:
- CI
- Updated the integration tests to test the names.

tbv2: fix type names for std::optional

---

test/integration/inheritance_polymorphic.toml
test/integration/inheritance_polymorphic_diamond.toml
test/integration/inheritance_polymorphic_non_dynamic_base.toml
test/integration/thrift_unions.toml

Some integration tests have not been updated since drgn started reporting type names with all their namespaces, and were failing.
Running the tests now report 15 failure, instead of 32 previously. The polymorphic tests are still failing due to TypeGraph not supporting them yet.

Add namespaces to integration tests' "typeName"

---

test/integration/std_tuple.toml

tbv2: update tuple test
This test is a bit odd, but this change adds the full set of size/member checks
for the hierarchy for TreeBuilder v2 and enables it.
Closes #304
Test Plan:
- CI

tbv2: update tuple test

---

test/integration/std_list.toml
test/integration/std_list_del_allocator.toml
types/cxx11_list_type.toml
types/list_type.toml

tbv2: correctly account for list overhead
`std::list` has per element overhead for the individual heap allocations. This
was already calculated in the container implementation but not used. Allocate
the overhead of each element in the `std::list` to the `std::list` itself as
with other sequential containers.
Test Plan:
- CI
- Updated test cases
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/455).
* #452
* #456
* __->__ #455

tbv2: correctly account for list overhead

---

oi/FuncGen.cpp
oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
test/integration/arrays.toml
test/test_topo_sorter.cpp

tbv2: name array member types correctly
Array members are currently being named "TODO" (whoops). Include arrays in
TopoSorter so each one can have a `NameProvider` generated in CodeGen. Then
pass array elements through `make_field`.
Test plan:
- CI
- Add array member names to an array test.
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/facebookexperimental/object-introspection/pull/456).
* #452
* __->__ #456

tbv2: name array member types correctly

---

include/oi/exporters/Json.h
include/oi/exporters/inst.h
include/oi/result/Element.h
oi/CodeGen.cpp
oi/FuncGen.cpp
oi/IntrospectionResult.cpp
test/integration/simple.toml
types/f14_fast_map.toml
types/f14_node_map.toml
types/f14_value_map.toml
types/f14_vector_map.toml
types/map_seq_type.toml
types/multi_map_type.toml
types/std_map_type.toml
types/std_unordered_map_type.toml
types/std_unordered_multimap_type.toml

tbv2: add is_primitive to output
C++ has a concept of Primitive which holds in the type graph. However we don't
currently expose this information to the end user. Expose this from the OIL
iterator to allow future features like primitive rollups.
This affects containers like maps which have a fake `[]` element with no type.
They use this to group together the key/value in a map and to account for any
per element storage overhead. Currently the decision is to make the fake `[]`
element a primitive if all of its children are primitives. This allows for more
effective primitive rollups if that is implemented. This implementation detail
may be changed in future.
Test Plan:
- CI
- Updated simple tests.

tbv2: add is_primitive to output

---

test/integration/README.md
test/integration/anonymous.toml
test/integration/arrays.toml
test/integration/bitfields.toml
test/integration/cycles.toml
test/integration/gen_tests.py
test/integration/inheritance_polymorphic.toml
test/integration/inheritance_polymorphic_diamond.toml
test/integration/inheritance_polymorphic_non_dynamic_base.toml
test/integration/pointers.toml
test/integration/pointers_function.toml
test/integration/pointers_incomplete.toml
test/integration/std_smart_ptr.toml
test/integration/thrift_isset.toml
test/integration/thrift_isset_missing.toml
test/integration/thrift_namespaces.toml

test: add features field to integration tests
Previously we tested different feature flags by using the `cli_options` field
in the test `.toml`. This works for OID but doesn't work for JIT OIL and won't
work for AoT OIL when those tests get added.
This change adds a new higher level `features` field to the test `.toml` which
adds the features to the config file as a prefix. This works with all methods
of generation.
Change the existing `cli_options` features to `features` except for where
they're testing something specific. Enable tests that were previously disabled
for OIL but only didn't work because of not being able to enable features.
Change pointer tests that are currently broken for OIL from `oil_disable` to
`oil_skip` - they can work, but codegen is broken for them at the minute. …

test: add features field to integration tests

---

include/oi/exporters/Json.h
oi/CodeGen.cpp
oi/OITraceCode.cpp
oi/type_graph/ClangTypeParser.cpp
oi/type_graph/DrgnParser.cpp
oi/type_graph/Types.h
test/integration/enums.toml
test/integration/thrift_isset.toml
test/integration/thrift_isset_missing.toml

tbv2: support capture-thrift-isset
Support the capture-thrift-isset feature with TreeBuilder-v2. Fairly minor
changes here except the type of the Enum in a template parameter now matters.
We follow the previous behaviour of capturing a value for each field in a
struct that has an `isset_bitset`. This value is a VarInt captured before the
C++ contents of the member. It has 3 values: 0 (not set), 1 (set), and 2
(unavailable). These are handled by the processor and represented in the output
as `false`, `true`, and `std::nullopt_t` respectively.
Changes:
- Add a simple Thrift isset processor before any fields that have Thrift isset.
- Store the fully qualified names of enum types in DrgnParser - it already
worked out this information anyway for naming the values and this is
consistent with …

tbv2: support capture-thrift-isset

---

oi/CodeGen.cpp
oi/FuncGen.cpp
oi/FuncGen.h
oi/type_graph/TopoSorter.cpp
oi/type_graph/TopoSorter.h
test/integration/anonymous.toml
test/integration/pointers.toml
test/integration/pointers_incomplete.toml
test/test_topo_sorter.cpp

tbv2: fix pointer codegen
A previous change enabled running OIL tests with specific features enabled.
This highlighted that pointer code generation under TreeBuilder-v2 was very
broken. This change updates pointer code generation to work and enables the
skipped tests. All enabled tests need `expected_json_v2` added to them due to
formatting differences.
Reformatted and rewrote the basic type handler that handles primitives and
pointers. Removed the reliance on `features` to decide whether to generate for
TreeBuilder-v2 as the intermediate features have been removed. Pointers are
treated as containers with a capacity of 1 and a length of 0 if null/a cycle
and 1 if followed. This holds for void pointers where, although they aren't
followed, the length is still set.
There were a couple of …

tbv2: fix pointer codegen

---

oi/type_graph/AlignmentCalc.cpp
oi/type_graph/ClangTypeParser.cpp

type_graph: avoid overwriting explicitly set alignment
Previously AlignmentCalc calculates the alignment and sets packing for every
type except a member with explicit alignment. Change this to check whether an
alignment has been previously set for a type before calculating it. Use this in
ClangTypeParser where the full alignment of the type is available.
Remove explicitly aligning members by the type because that was previously
reserved for members with explicit alignment. AlignmentCalc will correctly
align a member to the underlying type without this. Explicit member alignment
is still missing, as before this change.
Test plan:
- CI
- Too little. Gets further into a production type than without this change.

type_graph: avoid overwriting explicitly set alignment

---

oi/CodeGen.cpp
test/integration/thrift_isset.toml

tbv2: fix Thrift isset lookups with padding
Thrift isset was failing with a SEGV if the struct contained padding. This is
because we indexed the `isset_indexes` data structure using our field index
rather than the index of the field in Thrift. This then gave a rubbish index
for any exceeding which happens if we have added padding in the middle of the
struct, and this index was looked up in the bitset which can cause a SEGV.
Track a new index `thriftFieldIdx` which is only incremented if we've looked up
a Thrift index.
Namespaced the generated Thrift structs while I was there. This isn't necessary
anymore but cleans things up.
Test plan:
- Added a test case with lots of padding. These don't run in the CI but it
passes locally.
- `FILTER='OilIntegration.*' make test` - no failures
- …

tbv2: fix Thrift isset lookups with padding

---

test/integration/std_deque.toml
test/integration/std_deque_del_allocator.toml
types/deque_list_type.toml

Implement Container V2 for std::deque libstdc++ implementation. Fixes #316 
The OIL tests have been enabled and their values updated.

Implement Container V2 for std::deque

---

oi/CMakeLists.txt
oi/ContainerInfo.cpp
oi/ContainerInfo.h
oi/OICodeGen.cpp
oi/type_graph/ClangTypeParser.cpp
oi/type_graph/IdentifyContainers.cpp
oi/type_graph/TypeIdentifier.cpp
test/test_container_info.cpp

Summary:
OI was previously using `std::regex_match` to match container names. This was bad because `libstdc++`'s implementation of regex is awful. In the case of limited inlining it was causing a stack overflow when running CodeGen for large types (I think types with large names but I never got to the bottom of it).
Replace this with the competent `boost::regex_match` that we already have a dependency on.
Differential Revision: D53002752

container_info: switch to boost::regex

---

oi/OITraceCode.cpp
types/cxx11_string_type.toml
types/fb_string_type.toml
types/small_vec_type.toml
types/string_type.toml

The sso flag in string types was calculated wrongly:
```
containter.data() >= &container && containter.data() < (&container + sizeof(container))
```
But because the `&container` is of type `std::basic_string<>*` the + already multiplies by sizeof.
Some other types had similar problem, so I have changed them too.

fix string type sso computation

---

oi/CodeGen.cpp
oi/type_graph/KeyCapture.cpp
oi/type_graph/Printer.cpp
oi/type_graph/TopoSorter.cpp
oi/type_graph/Types.h
oi/type_graph/Visitor.h
test/integration/capture_keys.toml
test/test_key_capture.cpp

If a map in an object is typedef'd then we fail to identify the map as a container and ignore it as the target for key capture.
e.g.
```
using Foo = std::map<int, int>;
class Bar {
Foo myMap;
};  
```
Currently the following config with the above definition would fail to capture keys in maMap:
```
[[codegen.capture_keys]]
type = "Bar"
members = ["myMap"]
```
I've added a new integration test 'capture_keys_typedef' and a unit test.
There are more changes here than first thought needed but the reviewers ar well aware :-) .

Make KeyCapture work with nested typedefs

---

oi/FuncGen.cpp
test/integration/std_smart_ptr.toml
types/shrd_ptr_type.toml
types/uniq_ptr_type.toml

tbv2: use std::decay_t with smart pointers
CodeGen v2 permits template parameters to be qualified. This means that if we
call `make_field` with a template parameter it will be qualified. However, we
don't qualify the types when generating meta functions such as `NameProvider`
and `TypeHandler`. This means these qualified types don't match up with the
expected type.
Use `std::decay_t` when forwarding the type to `NameProvider` and `TypeHandler`
so they're always the base type that they were generated with. Most of this is
covered by `make_field`, but there are direct references to `TypeHandler<Ctx,
T>` in a lot of `TypeHandler::type` fields. Fix the problematic types manually
for now, there may need to be a better solution with meta functions for this in
the future.
Test Plan:
- CI
- Added …

tbv2: use std::decay_t with smart pointers

---

oi/type_graph/ClangTypeParser.cpp

Summary: Adding support for the nullptr clang type (clang::BuiltinType::NullPtr). While there I augmented the exception message to include the type name that is missing.
Differential Revision: D53272742

stub clang::BuiltinType::NullPtr primitive type

---

oi/OICompiler.cpp

C++17 defines the `__cpp_aligned_new` feature test macro and and according to https://en.cppreference.com/w/cpp/feature_test this is included in the `cxx17_core` group of feature test macros. In the 'new' header file this feature test is used to gate the definition of `std::align_t`. However, it appears that clang15 with `-std=c++20` somehow doesn't enable this feature flag and therefore code that we define that uses a `std::align_t` fails to compile.
Looking at the clang source (https://clang.llvm.org/doxygen/InitPreprocessor_8cpp_source.html) the `__cpp_aligned_new` feature macro is enabled separately to the block of cxx17 macros and is under the `AlignedAllocation` langopt. I'm not sure why this is so but we'll justset the language option in the driver and that appears to work fine. …

std::align_t fix

---

oi/CodeGen.cpp

Stubbing out a type that is used in a template parameter (e.g., the first parameter in a unique_ptr - types that we actually recurse into) means that `make_field` will be called on the stubbed type. This fails as we have no NameProvider instantiation for this newly created stubbed type. This fix simply adds a template specialisation for any stubbed types in the NameProvider implementation.
Tested internally.

Handle stubbed types in NameProvider

---

README.md
website/docusaurus.config.js

Adds CppCon 2023 presentation links to the README and the website.
- `cd website && yarn start` - it works

add cppcon presentation links

---

include/oi/IntrospectionResult-inl.h
include/oi/IntrospectionResult.h
include/oi/result/Element.h
include/oi/result/SizedResult-inl.h
oi/IntrospectionResult.cpp

tbv2: remove unnecessary copy in Element
`IntrospectionResult::const_iterator` iterates through the `Element`s in an
`IntrospectionResult`. `Element` currently copies the `type_path` which is a
`std::vector<string_view>` every time the iterator is incremented. This is
unnecessary as the data in the vector only changes slightly between iterations.
This change changes the `type_path` field in `Element` to a
`std::span<const std::string_view>`. Doing this previously caused SEGVs because
of the iterator's potential to be copied. To make it possible we do two things:
1. Make all copies explicit using a clone interface as in `ContainerInfo`. This
prevents accidental copies of an expensive structure.
2. After calling the copy constructor in `clone()` update the `span` in `next_`
to point at the …

tbv2: remove unnecessary copy in Element

---

oi/OIGenerator.cpp
oi/type_graph/ClangTypeParser.cpp
oi/type_graph/ClangTypeParser.h

This diff provides the ability to stub types via config in ClangTypeParser. Each type should be listed individually in extra config.
Tested internally.
CI.

stub types in OIL via config

---

oi/OIGenerator.cpp
oi/type_graph/ClangTypeParser.cpp
oi/type_graph/ClangTypeParser.h

Summary: Implement the pass-through feature in ClangTypeParser (keeping template parameters for specified types0.
Reviewed By: JakeHillion
Differential Revision: D53815662

Keep template parameters for pass-through types

---

oi/type_graph/ClangTypeParser.cpp
oi/type_graph/ClangTypeParser.h

Summary: Add support in ClangTypeParser for parents.
Reviewed By: JakeHillion
Differential Revision: D53708619

clangparser: add support for parents

---

.circleci/config.yml
.github/workflows/object-introspection.yml

convert circleci lint job to github actions
Start the migration from CircleCI to GitHub Actions with migrating the lint
job. Used the structure from @robandpdx to setup Nix and use a GitHub key.
Restructured the check from `nix flake check` to
`nix fmt; git diff --exit-code` so we get a full patch again.
Test plan:
- Submitted this PR with a formatting error. CI failed. Submitted without and
it passed.
Co-authored-by: Rob Anderson <robandpdx@github.com>

convert circleci lint job to github actions

---

oi/CodeGen.cpp
oi/ContainerInfo.cpp
oi/ContainerInfo.h
test/integration/std_variant.toml
types/README.md
types/std_variant.toml

tbv2: update std::variant
`std::variant` is the last archetypal container missing in TreeBuilder-v2. The
code for it isn't hugely complicated and relies on pack expansion.
This change introduces a new field to the container specification:
`scoped_extra`. This field allows you to write extra code that will be included
within the TypeHandler in CodeGen. This means it will not have collisions with
other containers, unlike the existing `extra` field. It's used here to write
the recursive `getSizeType` function for `std::variant`.
Tech debt is introduced here by comparing the container name to `std::variant`
in CodeGen to conditionally generate some code. We've worked hard to remove
references to containers in code and move them to `.toml` files. On balance,
this is worth having to include the …

tbv2: update std::variant

---

types/folly_optional_type.toml

Summary: The container implementation for `folly::Optional` currently lacks TBv2 support. This change is a skilfully crafted cut-n-paste of the `std::optional` TBv2 implementation.
Reviewed By: ajor
Differential Revision: D56139280

Make folly::Optional TBv2 compliant

---

CMakeLists.txt
test/integration/CMakeLists.txt

Bump python version to 3.9 for Centos9
No new failed tests seen with a `make test`.

bump python version to 3.9

---

oi/type_graph/ClangTypeParser.cpp
oi/type_graph/ClangTypeParser.h

This diff implements the handling on a clang::MemberPointer. We simply stub the type.
A 'make test` shows no new failures.

ClangTypeParser: handle clang::MemberPointer

---

oi/type_graph/ClangTypeParser.cpp

If a class inherits from more than one base class Clang Parser currently calculates incorrect offsets for everything but the first base class. This is owing to the fact that TypeGraph needs offsets in bits but ClangParser is providing them in bytes.
`make test` contains no additional failures. This was tested internally against a Meta source base.

Correct offset calculation with multiple base classes

---

oi/CodeGen.cpp

Currently in TypeGraph when generating inst::Field objects in the generated source we use the `sizeof` operator to construct the static and exclusive size. As you can't use sizeof() on a bitfield this generates invalid code. This fix special cases bit fields and sets the static and exclusive size to 0 as there size will be rolled up in the parent object.
A 'make test` has no new failures. This fix was tested against an object in a Meta source base.

TypeGraphv2: correctly handle bitfields in code generation

---

CMakeLists.txt
extern/shim-folly-config.h

Currently we pull a modified folly repository to be able to use it header only.
The only difference in this repository is adding the `folly-config.h` file.
Pull this patch into this repo instead and use upstream folly.
Bump folly to latest main as well.
Test plan:
- CI build. I have local build issues at the moment.

build: remove dependency on modified folly repository

---

oi/OICompiler.cpp

Summary:
Adjust object-introspection code to LLVM upstreaming moving `Host.h` around. See also:
* https://github.com/llvm/llvm-project/commit/e1e34cc2a17c5f640333767df2d3bfe2b2f81a84
* https://github.com/llvm/llvm-project/commit/f09cf34d00625e57dea5317a3ac0412c07292148
Differential Revision: D61363387

LLVM upstream removed Support/Host.h

---

oi/OICompiler.cpp

Summary: LLVM-18 changed the `CompilerInvocation` APIs to return references instead of pointers...
Differential Revision: D61548431

Adjust object-introspection to llvm-18 API changes

---

.circleci/config.yml
.github/workflows/ci.yml
.github/workflows/test-report.yml
CMakeLists.txt
flake.nix

Add LLVM-16 to the Nix builds and CI matrix. Also add the option to explicitly
select an LLVM version so the CircleCI build can still work as before.
We should support at least LLVM-17 currently, but there appears to be a
significant performance regression in compiling the generated code for large
variants that I'm going to debug separately. The long term goal is to support
and test all versions 15 and up.
Test plan:
- CI

build and test LLVM version 16

---

cmake/StandardProjectSettings.cmake
oi/CMakeLists.txt
oi/Descs.cpp
oi/Descs.h
oi/OICompiler.cpp
oi/arch/Arch.h
oi/arch/aarch64.cpp
oi/arch/x86_64.cpp

Summary:
OI is currently completely incompatible with anything except `x86_64`. Changing that generally is a big effort, but `oilgen` should work on other architectures. Begin adding some support for `aarch64` architecture.
This change sets up a file structure for architecture support. It pulls the 2 functions needed to make `Descs.{h,cpp}` architecture agnostic into architecture specific files for `x86_64` and `aarch64`. This enables `oilgen` (the binary) to build. At this stage `oilgen` is unable to generate working code for `aarch64`, but at least this is a step in the right direction.
Differential Revision: D61661524

add minimal support for aarch64

---

website/yarn.lock

Final (for now) attempt to get rid of dependabot warnings. The partial upgrades
seem to have messed things up a bit.
Test plan:
- `yarn upgrade`
- `yarn start`
- Looks fine.

website: yarn upgrade

---

website/package.json
website/yarn.lock

Dependabot raises regularly warnings about the dependencies used for the Docusaurus website. In particular, Docusaurus v2 is not maintained anymore and it uses NodeJS 16, which also reached its end of life.
This PR updates the website to use the current version of Docusaurus and removes multiple dev dependencies that were broken or unused.
The main breaking change comes from the MDX templates being updated to v3. Our MDX are simple enough to be compatible with the new version.
```
$ npx docusaurus-mdx-checker
[SUCCESS] All 8 MDX files compiled successfully!
```
Then doing a visual check through all our pages confirm the website stays identical to the previous version.
```
$ # Build and test the website locally
$ yarn build
[...]
$ yarn serve
```

Upgrade to Docusaurus v3

---

.github/workflows/ci.yml
CMakeLists.txt
flake.lock
flake.nix
oi/Descs.cpp
oi/OID.cpp
oi/OIDebugger.cpp
oi/SymbolService.cpp
test/integration/folly_shims.cpp
tools/config_gen.py

Update system dependencies with `nix flake update`. This update comes
with a bunch of formatting changes, but the most significant change is
dropping support for LLVM 15. With enough Nix work this can be avoided,
and it's unfortunate because LLVM 17 is as yet unsupported (by memory a
big perf regression in compilation speed), so we'll only support one
version for a while. I think it makes more sense given the current
state of the project to localise all users on exactly one working config
than attempt to support multiple.

chore(deps): lock file maintenance
